### ISSUE TITLE
Changed settings in the cfg file are ignored

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#10]
When I change settings in the yapb.cfg file, they don't work (for example I set yb_difficulty to 2 in the file, but when I start a server, bot difficulty is reset to the default value, 4)

**Comment by jeefo** [comment]
No it's not. Just tested, the values of yapb.cfg is applied as the should.

**Comment by leopard20** [comment]
Yeah. Sorry. I wasn't using the latest build.
