### ISSUE TITLE
Cashing with yapb

### ISSUE THREAD

**Issue by charis2324** [jeefo/yapb#102]
With yapb, CS 1.6 sometimes crashes at the stage of "Parsing Game info" when loading in the map.
I'm not sure it is 100% yapb causing the problem, but it seems only to happen when I have yapb installed. The issue can somehow temporarily be solve by restarting CS a couple of times( 5+). However, it will happen again when the game is closed. 

Build used: https://yapb.ru/files/binaries/5734/release/yapb.dll

**Comment by PRinceBhai** [comment]
Have you tried this github release?

**Comment by Fixer-007** [comment]
Please provide more information

**Comment by charis2324** [comment]
The github release is stabler. The same problem did not happen. However, using the git release, when I spectate the bots, the way they move their cursors is very laggy(not fps problem) which does not happen in the build I mentioned above(build 5734). I prefer playing with the newer build. The bots, generally, move a lot smoother and realistic compared to the git release.

**Comment by jeefo** [comment]
Hello. Hlds? Map? Mods?

**Comment by jeefo** [comment]
Closed as there is no response.
