### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by shoka95** [jeefo/yapb#103]
can you make waypoints for thеse maps
http://www.onestrike.eu/maps/ONESTRIKE-cs_inferno_2x2.zip
http://www.onestrike.eu/maps/ONESTRIKE-fy_parkett.rar
https://www.17buddies.rocks/17b2/View/Map/88118/de_dust2_bb.html

https://www.17buddies.rocks/17b2/View/Map/53974/de_mini_train2.html

**Comment by mastatekilla** [comment]
I also need cs_inferno_2x2 and de_mini_train2 waypoints. Can someone create wp for them please ? I will be grateful.

**Comment by Overitab** [comment]
[fy_parkett.zip](https://github.com/jeefo/yapb/files/3770469/fy_parkett.zip)
[de_dust2_bb.zip](https://github.com/jeefo/yapb/files/3770566/de_dust2_bb.zip)

**Comment by shoka95** [comment]
if you can give pwf files, these have bugs

**Comment by shoka95** [comment]
Thank you very much, but is it possible to convert them to pwf files ? I use the latest available version, but the server crash when i use graph files.. i don't know why.

**Comment by Overitab** [comment]
i dont know how convert to pwf, i make from yapb. Sorry not have time to make now from podbot. Better send log file and you config, to jeefo look why crash

**Comment by jeefo** [comment]
Can you provide more information about crashes?

**Comment by shoka95** [comment]
Sorry for the late response. The problem was in other plugin, and now i can use graph files without a problem. Thank you : )
