### ISSUE TITLE
Weapon Configuration

### ISSUE THREAD

**Issue by mastatekilla** [jeefo/yapb#104]
Hello. Is it possible to configurate wich weapons the bots can use ? I already try with some changes in general.cfg but without results. I want to restrict them to play with automatic snipers and awp.

**Comment by Nakaxhan** [comment]
Try changing this lines in general.cfg

```
//
// The following Tables stores the Weapon Priorities of the Bots depending on
// Personality (it affects buying & picking up better weapons from the ground).
//
PersonalityNormal = 0,1,5,2,4,6,3,7,10,12,8,20,25,22,13,11,9,24,17,15,19,18,16,14,23,22,21
PersonalityRusher = 0,1,2,5,6,4,3,20,7,25,10,9,12,8,13,11,18,17,24,15,19,16,14,22,23,21
PersonalityCareful = 0,5,2,4,3,1,6,8,7,10,12,24,13,9,11,17,20,25,18,15,14,16,19,22,23,21

//
// Following are Tables which specify which Team is allowed
// to buy a weapon on a Map. You can also use it to allow/disallow
// Weapons for a Team or a Map/Gamemode (remember that some
// Weapons are team-specific and can't be bought by another team).
// -1 = Disallow Buying for any Team
// 0 = Terrorist Team only
// 1 = CT Team only
// 2 = Can be bought by both Teams
// Standard Weapon Tab for CS & DE Maps
//


MapStandard = -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,2,-1,-1
MapAS = -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,2,-1,-1

```

**Comment by mastatekilla** [comment]
I alreay try, but they still playing with all weapons. And also this cvar in yapb.cfg - yb_restricted_weapons "" is it important ?

**Comment by Nakaxhan** [comment]
Oh, I think that this is the problem.
You need to add any weapon name you want to restrict, separeted by semicolon
See more about it here [https://yapb.readthedocs.io/en/latest/configuring.html](url)

**Comment by mastatekilla** [comment]
Same thing. No result :(

**Comment by jeefo** [comment]
yb_restricted_weapons "g3sg1;sg550;awp"

**Comment by mastatekilla** [comment]
> 
> 
> yb_restricted_weapons "g3sg1;sg550;awp"

exactly the same thing i tried. I think the cvars didn't work. I use the latest linux version. Which version should i use ?

**Comment by jeefo** [comment]
What you expect to see? Bot's shouldn't buy them. But will try to pickup them if available.

Try: https://yapb.ru/files/binaries/5734/release/

**Comment by mastatekilla** [comment]
Everything is okay now. Thanks for the help. Cheers

**Comment by jeefo** [comment]
Great!
