### ISSUE TITLE
Переход на нож при сближении

### ISSUE THREAD

**Issue by ZGBarmaleyPetrovich** [jeefo/yapb#105]
Привет.
Возможно ли убрать у ботов переключение на нож при сближении с ним? Так же бывают ситуации, когда бот просто не стреляет.
Использую последний билд.

**Comment by jeefo** [comment]
Привет.

Реалзую на следующей неделе.

**Comment by ZGBarmaleyPetrovich** [comment]
Спасибо! Будем ждать.

**Comment by jeefo** [comment]
В последнем билде yb_stab_close_enemies.

**Comment by ZGBarmaleyPetrovich** [comment]
> В последнем билде yb_stab_close_enemies.

Спасибо! Протестил, теперь не пытаются резать и вроде не тупят.

Если позволишь, несколько вопросов (не хочется пложить новые темы).
1. Можно ли настроить процент использования гранат, флешек и дымовых? Использую ботов в своем моде, выдавая им оружие и гранаты (запрещая полностью покупку ) Не пойму, когда они решают кидать гранаты, Они их очень не охотно используют. Было бы супер иметь параметр, который регулировал частоту использования всех видов гранат.
2. Подскажи пож-та, как командой(не через меню управления ботами) через консоль сервера добавить бота (имеется ввиду синтаксис)?

**Comment by Lolasik011** [comment]
@ZGBarmaleyPetrovich Скажешь пожалуйста как установить последний тестовый билд ботов ?

**Comment by ZGBarmaleyPetrovich** [comment]
> @ZGBarmaleyPetrovich Скажешь пожалуйста как установить последний тестовый билд ботов ?

https://yapb.ru/files/binaries/
Выбираешь в зависимости от ОС, на которой работают боты и кидаешь в addons\yapb\bin

**Comment by jeefo** [comment]
> > В последнем билде yb_stab_close_enemies.
> 
> Спасибо! Протестил, теперь не пытаются резать и вроде не тупят.
> 
> Если позволишь, несколько вопросов (не хочется пложить новые темы).
> 
> 1. Можно ли настроить процент использования гранат, флешек и дымовых? Использую ботов в своем моде, выдавая им оружие и гранаты (запрещая полностью покупку ) Не пойму, когда они решают кидать гранаты, Они их очень не охотно используют. Было бы супер иметь параметр, который регулировал частоту использования всех видов гранат.
> 2. Подскажи пож-та, как командой(не через меню управления ботами) через консоль сервера добавить бота (имеется ввиду синтаксис)?

Кидание гранат для ботов довольно сложное занятие, проценты можно вывести в квар, но чтобы бот кинул должно сойтись очень много условий.

`yb add [difficulty[personality[team[model[name]]]]]`

для того чтобы добавить бота с имененм Vasya и рандомными параметрами можно наборать: `yb add * * * * Vasya`.

**Comment by ZGBarmaleyPetrovich** [comment]
> > > В последнем билде yb_stab_close_enemies.
> > 
> > 
> > Спасибо! Протестил, теперь не пытаются резать и вроде не тупят.
> > Если позволишь, несколько вопросов (не хочется пложить новые темы).
> > 
> > 1. Можно ли настроить процент использования гранат, флешек и дымовых? Использую ботов в своем моде, выдавая им оружие и гранаты (запрещая полностью покупку ) Не пойму, когда они решают кидать гранаты, Они их очень не охотно используют. Было бы супер иметь параметр, который регулировал частоту использования всех видов гранат.
> > 2. Подскажи пож-та, как командой(не через меню управления ботами) через консоль сервера добавить бота (имеется ввиду синтаксис)?
> 
> Кидание гранат для ботов довольно сложное занятие, проценты можно вывести в квар, но чтобы бот кинул должно сойтись очень много условий.
> 
> `yb add [difficulty[personality[team[model[name]]]]]`
> 
> для того чтобы добавить бота с имененм Vasya и рандомными параметрами можно наборать: `yb add * * * * Vasya`.

Реально ли сделать кваром увеличение шансов использования гранаты (уменьшить кол-во условий)?

Personality - Normal/Rusher/Careful ?

**Comment by jeefo** [comment]
random = *
  Normal = 0
  Rusher = 1
  Careful = 2
