### ISSUE TITLE
How do I remove spam from radio chat commands?

### ISSUE THREAD

**Issue by stambeto2006** [jeefo/yapb#106]
@jeefo How can I prevent bots from constantly spamming radio commands in chat? Because whatever I try, no effect.

**Comment by jeefo** [comment]
Yup. Chatter is fixed now, but radio is still spamming.

Will try to fixed asap.

**Comment by stambeto2006** [comment]
@jeefo When is it expected to be fixed?

**Comment by jeefo** [comment]
Can you try latest build ?

**Comment by jeefo** [comment]
Sorry, and can you record a little video?

**Comment by stambeto2006** [comment]
@jeefo How can I download the latest version you released that I can't find?

**Comment by jeefo** [comment]
https://yapb.ru/files/binaries/5787/

**Comment by stambeto2006** [comment]
Now everything is fine and there is no spam.
