### ISSUE TITLE
Need some waypoints

### ISSUE THREAD

**Issue by mastatekilla** [jeefo/yapb#107]
Hello again. I'm looking for waypoints for some small maps. I will be grateful if someone can create it. No matter if they are graph or pwf files. Thanks : )

Here is the maps:
https://www.17buddies.rocks/17b2/View/Map/53218/gg_cbble.html
https://www.17buddies.rocks/17b2/View/Map/59637/fy_dust_largo.html
https://www.17buddies.rocks/17b2/View/Map/91423/aim_smalldgl.html
https://www.17buddies.rocks/17b2/View/Map/71215/fy_forge_beta.html
https://www.17buddies.rocks/17b2/View/Map/56169/dem_kdust.html

**Comment by Overitab** [comment]
[gg_cbble.zip](https://github.com/jeefo/yapb/files/3801316/gg_cbble.zip)
you have steam or other contacts ?

**Comment by mastatekilla** [comment]
Thanks. You can find me in skype: mastatekilla discord: mastatekilla#5932 or mastatekilla@gmail.com
