### ISSUE TITLE
Full eco / semi-eco rounds?

### ISSUE THREAD

**Issue by Nakaxhan** [jeefo/yapb#108]
I think it would be very useful if the bots did full eco/semi-eco rounds (eg. default pistol + kevlar, pistol only, only pistol + grenade). In my case, every time they do an eco round, they waste money 90% of the time in grenades and 100% in Kevlar+Helmet. If they die without kill someone, the next round they don't have enough founds to buy a rifle and they return to the same eco.

**Comment by jeefo** [comment]
Will look into this.
