### ISSUE TITLE
Yapb's Spray 

### ISSUE THREAD

**Issue by charis2324** [jeefo/yapb#109]
When the enemy comes close and yapb decides to spray, sometimes, it won't stop spraying even though its corsair is already above the enemy's head due to the recoil. As a result, it misses those shots which doesn't look realistic. I think it would be useful to add some simple spray control or better checks to stop shooting when its corsair is not on hitbox of enemies.

yapb build used: 5734

**Comment by jeefo** [comment]
Hi.

https://yapb.ru/files/binaries/5787/

Please test.
