### ISSUE TITLE
Bots ignore their goal priority

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#11]
Like I said before, bots don't go after their primary goal (for example terrorists don't plant the bomb, or even when they want to, they are distracted by the enemy, even when they just hear their footsteps). They just kill each other. It's like I'm playing CSDM!

**Comment by leopard20** [comment]
Ok, I played for a little longer. Sometimes bots plant the bomb, but after nearly 4 minutes has passed. It looks like they just move around the map aimlessly until they find the bomb site, then plant it. The game gets so boring because of this.
Also bots don't attack in numbers. They work solo. It would be better to add some teamwork to their AI.

**Comment by leopard20** [comment]
Two more thing about bot AI that needs to be fixed are:
1) bots take cover in open areas, instead of near walls or behind objects.
2) they don't have much variety in their attacks, for example, in de_dust 2 map, almost each round I noticed 3 bots to attack from the 'double doors', and 4 to go to bomb site B. They never used the 'side door' to attack. So I always knew how to kill them. 

If you fix these AI issues, the game will be a lot more fun to play.

**Comment by jeefo** [comment]
Yes, they prefer to fight instead of doing goal. But they doing the goals most of time.

Teamwork... Well they running together, if enough players. The main reason bot has no teamwork or something, was the bug in hl engine, making bots stuck in each other every time they collide, so the code tries to send bots in different locations, so they won't collide. This will probably fixed in some next version.

About covering, they using somewhat "experience" system, and if this stuff saying: "This place is safe", they will use it.

About the variety of attack, try to delete data/learned folder, of the specific file for needed map. However i will try to randomize bots navigation a bit.

**Comment by leopard20** [comment]
Bot navigation needs some serious fixed, besides randomization of attacks. On certain maps, bots get stuck in certain places(for example, on office map, they get stuck behind the creates in the front yard). Or on some maps, it looks they don't know certain places (sometimes even the bomb sites!). For example on de_piranesi, they never plant the bomb(they don't even go near bomb sites, based on my experience).
Also, what is this obsession of theirs to spay tag? Sometimes they climb all the way up the crates for this. I always disabled this function for the bots.

**Comment by jeefo** [comment]
Much of navigation depends on hows the waypoints made.

**Comment by leopard20** [comment]
Also what is the difference between yb_debug_goal variables? Bots seem to behave similarly for any value other than the default value -1. (Terrorists stay in the t spawn, spraying tag, while CTs attack them and kill them all!)

**Comment by jeefo** [comment]
It's forces all bots to go to the waypoint specified in this cvar.

**Comment by leopard20** [comment]
Can you make their waypoint similar to that of  original cs bots? Because original bots seem to behave ok when it comes to going around the map.

**Comment by jeefo** [comment]
It's not possible in yapb.

**Comment by jeefo** [comment]
partially fixed in fixed in 8448bb3, pls create new issue if not completely.

**Comment by leopard20** [comment]
It's gotten a whole lot better. Bots still linger more than necessary but it's not really important.
