### ISSUE TITLE
Shooting through allies

### ISSUE THREAD

**Issue by charis2324** [jeefo/yapb#110]
I have seen a couple of times that yapb shot through allies(on server with teamkilling off) and killed enemies even though it didn't have sight for the enemy since its ally is blocking its vision which doesn't look like human.

yapb build used: 5734

**Comment by jeefo** [comment]
It's actually normal situation.

Bots vision skip player if line of sight is totally blocked. If bot shoots enemy (even thru a teammate), the bot actually sees him. It's not cheating.
