### ISSUE TITLE
Blocking each other

### ISSUE THREAD

**Issue by charis2324** [jeefo/yapb#111]
When yapbs decide to walk an opposite direction and meet, they body-block each other. If one tries to evade, let say, to the left, the other one does the same and they collide and blocking each other again. The process often repeats for a few times until they are able to wiggle away from another through some random movements. The issue is even funnier in a narrow corridor, for instance, the gap between doors in dust2. A few bots will be stuck there and wait for their death.

It will be much realistic if they can evade each other before their collision. 

yapb build used: 5734

**Comment by Overitab** [comment]
why not use semiclip plugin ? never play without this plugin

**Comment by jeefo** [comment]
Correct semiclip is not possible without using Regamedll or using offsets for normal gamedll, so please use plugin.

Actually bots try evade each other before getting into collision. But if ther're a walls around or other bots around, this checks are skipped. I will look into this when i have some time.
