### ISSUE TITLE
WayPoints for de_dust2_snow [Counter-Strike 1.6]

### ISSUE THREAD

**Issue by shoka95** [jeefo/yapb#113]
Guys i need waypoints for this map, can someone make it for me?
www.onestrike.eu/maps/ONESTRIKE-de_dust2_snow.zip

**Comment by jeefo** [comment]
@Overitab If you can, help please.

And can you try to use ``yb graph upload`` functionality to upload graph file to database.

**Comment by Overitab** [comment]
done
[de_dust2_snow.zip](https://github.com/jeefo/yapb/files/3907541/de_dust2_snow.zip)

https://github.com/jeefo/yapb-graph/issues/2

**Comment by jeefo** [comment]
@Overitab Thank you.
@shoka95 https://podbot.ru/files/binaries/5793/release/

You can install latest dll, and it will download latest waypoint/graph for you automatically.

**Comment by stambeto2006** [comment]
@Overitab @jeefo Can you make waypoints for these maps?
[https://gamebanana.com/maps/167547](url)
[https://www.17buddies.rocks/17b2/View/Map/61472/zm_evil-ice_attack2.html](url)
https://www.17buddies.rocks/17b2/View/Map/12525/sea_dust2.html

**Comment by stambeto2006** [comment]
@Overitab @jeefo Can you make waypoints for these maps?
1. zm_dex
2. zm_evil-ice_attack2
3. sea_dust2

**Comment by PRinceBhai** [comment]
@stambeto2006 Do you still need waypoints for these maps?

**Comment by stambeto2006** [comment]
> @stambeto2006 Do you still need waypoints for these maps?

yes

**Comment by jeefo** [comment]
They all uploaded to database. Recent builds should Auto download them...

**Comment by stambeto2006** [comment]
@Overitab @jeefo Can you make waypoints for these maps?

1. zm_battle_ground2
2. zm_crossfire10
3. zm_dust_jasionka
4. zm_dust2_final
5. zm_firezone
6. zm_heal_dust2
7. zm_hell_house_v4
8. zm_infantry
9. zm_laf
10. zm_lan_house
11. zm_militia
12. zm_mystic
13. zm_neris2
14. zm_toxic_house_vk

**Comment by stambeto2006** [comment]
@Overitab  @jeefo  @PRinceBhai  Will you make them?

**Comment by jeefo** [comment]
@stambeto2006 use #139 for Future requests.

Thank you.
