### ISSUE TITLE
Часто не стреляют находясь рядом вблизи

### ISSUE THREAD

**Issue by ZGBarmaleyPetrovich** [jeefo/yapb#114]
Jeefo, Привет.
Можешь подсказать, почему боты зачастую находясь в непосредственной близости с врагом не стреляют в него. Можно ли это как то пофиксить?
Пример: https://youtu.be/ymJhH0MVEUU
Проблема наблюдается не только в узких лабиринтах в положении сидя как показано в примере, так же и на открытой местности когда бот стоит и нему успеть подбежать, он так же почти никогда не стреляет. Использую последний билд 2.92.426.0

**Comment by stambeto2006** [comment]
@jeefo I noticed that at some point in the round, the bots stop firing and stand as if they are afk until the round is over and the new one starts.

**Comment by jeefo** [comment]
Yup. Its problem, when bot is out of ammo with pistols. Will try to fix

**Comment by jeefo** [comment]
@ZGBarmaleyPetrovich какая карта?

**Comment by ZGBarmaleyPetrovich** [comment]
> @ZGBarmaleyPetrovich какая карта?

cs_miami_cz

**Comment by ZGBarmaleyPetrovich** [comment]
Кстати забыл сказать, я забрал у них пистолеты, чтобы они с них вообще не стреляли. Только основное оружие.

**Comment by jeefo** [comment]
Странно, не могу воспроизвести... :(

**Comment by PRinceBhai** [comment]
No this is a bug, i've experienced this too but just rarely. I have no restrictions for the bots and even though they have ammo and weapons they just won't shoot in close proximity, either keep standing there or run away while looking at the opponent. @jeefo

**Comment by jeefo** [comment]
Probably will help:

https://podbot.ru/files/binaries/5832/release/

**Comment by ZGBarmaleyPetrovich** [comment]
> Probably will help:
> 
> https://podbot.ru/files/binaries/5832/release/

**Comment by ZGBarmaleyPetrovich** [comment]
> Странно, не могу воспроизвести... :(

И еще нож убрал, может в этом проблема

**Comment by jeefo** [comment]
Если и ножи отобраны, возможно нужно выставить yb_stab_close_enemies в 0, чтобы боты не пытались "резать" при приближении, а так как ножа нет, выходит "казус".

**Comment by PRinceBhai** [comment]
@jeefo Are you updating files on both yapb.ru and podbot.ru? If not then can you please tell me which one is more updated or what the difference is even in both sites?

**Comment by jeefo** [comment]
It's a same website. Just a different domains

**Comment by ZGBarmaleyPetrovich** [comment]
> Если и ножи отобраны, возможно нужно выставить yb_stab_close_enemies в 0, чтобы боты не пытались "резать" при приближении, а так как ножа нет, выходит "казус".

Мой косяк. Добавлял yb_stab_close_enemies "0" в конец yapb.cfg, а оказывается она оттуда не грузится.. Вызываю теперь эту команду после каждой смены карты и все ок.
