### ISSUE TITLE
CTs unable to defuse the bomb. Need help.

### ISSUE THREAD

**Issue by yu1338** [jeefo/yapb#115]
Sorry about my English!

I did try version 4626. 5306. 5318. 5395. 5832.
They are not working at defuse the bomb.
I try to set one goldpoint or many goldpoint in the bombside, still not defusing. 
CTs just walk around the bomb.

**Comment by jeefo** [comment]
hello.

please provide map & graph file.

**Comment by PRinceBhai** [comment]
Used to happen to me, but it was fixed in the latest releases, please provide your mapname and graph files.

**Comment by yu1338** [comment]
I found out the problem.
I did try 4 maps. Setting bots weapon knifes only. (unable to dufuse)
Otherwise.(enable to defuse)

**Comment by jeefo** [comment]
Should be fixed in latest release.

**Comment by yu1338** [comment]
Thank you!
It's 4.0 version now!
I will try later!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jeefo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上8:40
收件人:&nbsp;"jeefo/yapb"<yapb@noreply.github.com&gt;;
抄送:&nbsp;"Yu1337"<756128001@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jeefo/yapb] CTs unable to defuse the bomb. Need help. (#115)





 
Should be fixed in latest release.
