### ISSUE TITLE
Ability to use existing Graph data on another Map? 

### ISSUE THREAD

**Issue by PRinceBhai** [jeefo/yapb#117]
I assuming that this might already be requested or even put into the plugin, but i was wondering if there was a way to load a premade graph/waypoint file into another map. Because some custom maps created by mappers have 2-3 variants which means they are the same map but with little to no modifications like skybox being different and some props moved here and there and so on. So it'll be a good help in creating waypoints for these variants of the maps. I hope you consider this jeefo.

**Comment by jeefo** [comment]
Hello.

With .graph format u're not restricted to map. Graph doesn't check map consistency at all. You can just rename file and it should be loaded OK.

**Comment by PRinceBhai** [comment]
@jeefo Thanks, i actually tried this with the. wpf format before, i actually forgot that. graph were new and different. Thanks tho.
