### ISSUE TITLE
Bot radio chat spam.

### ISSUE THREAD

**Issue by iclassdon** [jeefo/yapb#118]
Hello,  I have used some of the builds suggested in this close issues section along with the latest build 5832. 

On build 5395 when changing command yb_communication_type "0" in config it does not work the bots keep on chattering non stop.  If I trigger in the console during gameplay it will disable it but in the next map it's right back to yb_communication_type "2" and they chatter once again.

On build 5832 yb_communication_type does not work at all and they still chatter  

I saw somewhere in a closed issue of another recommended build recommended to a user and it's exhibiting the same behavior.  Any way to get this annoying thing to stop spamming radio chatter?

BOT123 (RADIO): Hold This Position.
BOT123 (RADIO): Hold This Position.
BOT123 (RADIO): Hold This Position.

**Comment by PRinceBhai** [comment]
This was fixed on the recent builds, also the command was renamed to "yb_chatter_mode" or "yb_radio_mode" or something so better check that out.

**Comment by iclassdon** [comment]
I double checked and downloaded 2.9 again and there is no mention to the yb_radio_mode or yb_chatter_mode.  All I found in the config was yb_communication_type "2"

**Comment by PRinceBhai** [comment]
@iclassdon Are you downloading from the releases tab? If so then get the latest build from yapb.ru

**Comment by iclassdon** [comment]
I have tried the latest build instead as recommended.  It's the same thing.  The config has no reference to the commands you listed above.  It's still doing the same thing.

**Comment by jeefo** [comment]
Hello.

Prince right, in latest builds cvar named yb_radio_mode.

Latest build: https://yapb.ru/files/binaries/5832/release/

**Comment by PRinceBhai** [comment]
@iclassdon Try that in-game, the repository only have the binaries listed there, so the .cfg doesn't get updated, or in my case it didn't, also i just checked the command it's "yb_radio_mode" now.

**Comment by iclassdon** [comment]
Thanks that worked.
