### ISSUE TITLE
Ladder bug and dont shot with zoom

### ISSUE THREAD

**Issue by ZGBarmaleyPetrovich** [jeefo/yapb#119]
Jeefo, Привет!
Подскажи пож-та, возможно ли пофиксить два момента:
1. Если боты поднимаются по лестнице и сверху располагается враг, как только они его увидят сразу спрыгивают. Можно ли параметром сделать возможность чтобы они все таки сначала залезли до конца по лестнице и начали стрелять? Если стоять сверху они так и не могут подняться (к примеру на карте nuke)
2. Боты перестают стрелять из оружия с прицелом (awp, scout, скорострелки), если враг находится рядом с ними ( https://www.youtube.com/watch?v=uzWIHjy3Y5c ). 
Заранее благодарю, если найдешь время это пофиксить.

**Comment by jeefo** [comment]
Привет.

Вторичное оружие отобрано?

**Comment by jeefo** [comment]
По первому пункту, хз. Игнорить врагов пока на лестнице?

**Comment by ZGBarmaleyPetrovich** [comment]
Пистолеты отобрал. 
Да, можно ли сделать параметром  возможность игнора врага на лестнице? Просто забавно они все поднимаются и сразу спрыгивают и так в бесконечном цикле.

**Comment by jeefo** [comment]
@ZGBarmaleyPetrovich 
https://podbot.ru/files/binaries/5859/release/

**Comment by ZGBarmaleyPetrovich** [comment]
> @ZGBarmaleyPetrovich
> https://podbot.ru/files/binaries/5859/release/

Большое спасибо! Протестил, все супер.

**Comment by jeefo** [comment]
Resolved.
