### ISSUE TITLE
Bots see me/each other through walls

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#12]
I was hiding behind a door (I had crouched, and I wasn't moving, so they weren't hearing my footsteps). Then a bot, that was walking, and aiming at me, killed me. I have used that spot many times in multiplayer with bots (original bots, not yapb) and players, and they always fell for my trick. 
But it was like yapb bots knew I was hiding there. It wasn't the first time actually, they always do that. Even when other bots are hiding in bomb sites, the bomber goes to the hiding bot, kills him, and then plants the bomb. It's like they're using thermal goggles or something.

**Comment by jeefo** [comment]
Somewhat related to #9 as it's "superhearing"

Try to set yb_whose_your_daddy to 0. Latest builds should have this by default.
