### ISSUE TITLE
difficulty randomizer

### ISSUE THREAD

**Issue by shiqi586564** [jeefo/yapb#122]
suggestion:randomize the bot's difficulty in order to simulate human match

**Comment by jeefo** [comment]
Hello.

Do you mean like something auto-diffculty, raise or lower difficulty based on game play ?

Or just create bots with random difficulty?

**Comment by PRinceBhai** [comment]
@jeefo how about both?

**Comment by jeefo** [comment]
Maybe after project rename...

**Comment by jeefo** [comment]
Added:

yb_difficulty_min & yb_difficulty_max = the minimum and maximum bound for creating bots. If set to non -1, yb_difficulty ignored when creating bots.

yb_difficulty_auto - bots added with yb_difficulty, and every round balances it's difficulty based on team contribution and KD  ratio.
