### ISSUE TITLE
New versions yapb crashes my server!

### ISSUE THREAD

**Issue by danteswx** [jeefo/yapb#127]
Sorry for my poor english.

Yapb 5862 5896 5927 ubot 0.1.0.487 crashes my server.
Yapb 5859 is ok
same yapb.cfg used "yb cvars save" get from ver 5927.

My server info:
Debian 9 x64
Rehlds 3.7.0.695
Regamedll 5.15.0.458
Metamod-r v1.3.0.128
Reunion 0.1.0.135
Amxmodx 1.9.0 5263

**Comment by jeefo** [comment]
Hi. Crashes on load or during game?

**Comment by danteswx** [comment]
> Hi. Crashes on load or during game?

During game.

**Comment by jeefo** [comment]
any specific  map? needs more info... test servers runnings just fine...

@dmitryzhukov can you write msg to telegram.
