### ISSUE TITLE
Cant Delete Graph Data... And No Button/Switch Flags.

### ISSUE THREAD

**Issue by ForeskinJohn** [jeefo/yapb#128]
While waypointing for cs_italy2, that i had a waypoint file with the same name, simple enough. Although, once i have deleted the graph data for this map, the conflicting nodes still show up. Hell, i deleted my entire data folder and all my graph data and nodes were still placed. Is the graph data perhaps written to the binary once saved? or somewhere in my registry perhaps? This is all very confusing.... and on the second note, i have noticed that there is no button/switch commands, this is fine because the bots can learn to use a switch with map flags, although their use of said switches is VERY VERY rare and limited, and almost never proper. For example, the garage door near CT spawn in office is very rarely used, yet bots will still try to go through it as if it were open. can i perhaps use the "lift" flag to make these bots use these doors and switches properly? Or perhaps i am just too confident in this ai. Any response is greatly appreciated in this day and age, as support for this old game and its custom content will forever fade.

**Comment by jeefo** [comment]
Hello.

It's because bot auto-download graph file. You need to set "yb_graph_url" to "" in order to prevent bot from downloading graph file.

Button usage is currently limited, and there's no additional flags except "LIFT" for buttons, but lift should be used only for lifts, as it's searching for lift entity target to trigger.

**Comment by ForeskinJohn** [comment]
well, other than the slight issues ive seen, i truly have to say that this is the best bot mod ive seen for counter strike, not only are they quick with completing objectives, they seem to act the most like players that out of any bot ive seen, and they're easy to waypoint  for, thus, universalizing their compatibility. and tbh, with the switches, all i have to really do waypoint a map in the og pod bot with the switch flags and convert it and the bots will know right away, so i just want to end my tangent by saying thanks for keeping this so up to date, to you and the folks who started the POD Bot project way back of course. This game has truly been immortalized through these mods alone!
