### ISSUE TITLE
Time List real Players dont work

### ISSUE THREAD

**Issue by Infamous2017** [jeefo/yapb#129]
Since I started using Yapb Bots, real players have not been shown in the Time list. Look here:

 [ 6] YaPB             RUN   -    yapb.so                    v2.92           ini  Chlvl ANY
ReHLDS version: 3.7.0.696-dev
Build date: 18:46:47 May 18 2020 (2228)

https://funkyimg.com/i/35fwM.jpg

**Comment by jeefo** [comment]
Hello. Confirmed.

Temporary you can set ``yb_enable_query_hook`` to ``0`` in order to get it working.

**Comment by Infamous2017** [comment]
Sorry but i dont have this in the cfg.  So where i have to add this?

**Comment by Infamous2017** [comment]
dont work.

**Comment by Infamous2017** [comment]
OK now it works. i added it to server.cfg , game.cfg and amxx.cfg :D

**Comment by jeefo** [comment]
Nice.

Fix will be available in a  few days.

**Comment by jeefo** [comment]
Should be OK with: https://yapb.ru/files/release/4.0.0.443/
