### ISSUE TITLE
ВЛЮБЛЕННОСТЬ

### ISSUE THREAD

**Issue by sergiopoverony** [jeefo/yapb#13]
Боты бегут, увидели друг друга, их глаза встретились и любовь наполнила их сердца.. глаза в глаза... 
![screenshot_2016-01-25-09-32-12](https://cloud.githubusercontent.com/assets/5286127/12545381/85041abc-c363-11e5-8987-ba6666589db7.png)
![screenshot_2016-01-25-09-31-38](https://cloud.githubusercontent.com/assets/5286127/12545383/8bd82d88-c363-11e5-8e22-70e8cc2a6b54.png)

 А после пришли двое и любовались влюбленной парочкой

![screenshot_2016-01-25-09-31-58](https://cloud.githubusercontent.com/assets/5286127/12545385/93ae44a2-c363-11e5-9ae3-62a92880c0e8.png)
![screenshot_2016-01-25-09-31-23](https://cloud.githubusercontent.com/assets/5286127/12545386/93e45e3e-c363-11e5-8e0f-d4ddf75c1d3a.png)

**Comment by jeefo** [comment]
Будет замечательно, если при этом будет yb_debug 3. Трудно понять в каком стейте это произошло. На штатной КС, сейчас такого не происходит.

**Comment by sergiopoverony** [comment]
Дебаг по дефолту включен или нет?

**Comment by jeefo** [comment]
Нет.

**Comment by sergiopoverony** [comment]
Окей, ОН логирует в файл или консоль смотреть?

**Comment by sergiopoverony** [comment]
Миша сделал VGUI меню управления ботами - взяв за основу моё. Можешь сделать чтобы при данном скваре не отображалось текстовое меню? Алибек сделал для радио так. _extended_menus "1" по этой команде чтобы не отображалось - сможешь?

**Comment by sergiopoverony** [comment]
Вот у этого явно дебаг не мог считать - так как он в меня влюбился. Понял из за чего. Когда к ним в плотную подходишь - они тупят. Когда отойдешь - начинает стрелять... в итоге я с ним так возле банке бегал - тестировал его. Вычеслил про дальность и он меня убил 
![screenshot_2016-01-26-21-12-31](https://cloud.githubusercontent.com/assets/5286127/12587526/92affe92-c476-11e5-80ca-1dd2415c80ad.png)
![screenshot_2016-01-26-21-12-46](https://cloud.githubusercontent.com/assets/5286127/12587527/92b58bc8-c476-11e5-8bc9-38edf24bcb71.png)
![screenshot_2016-01-26-21-13-07](https://cloud.githubusercontent.com/assets/5286127/12587525/92abbae4-c476-11e5-948b-88a5c323e7da.png)

**Comment by jeefo** [comment]
Должно быть пофикшено в текущей ревизии, но не проверял. 

По поводу меню. Я не могу проверять клиентские cvar'ы, могу отключить цифры для всей сборки андройда.

**Comment by sergiopoverony** [comment]
Может свой сквар введешь? чтобы прятать его? 
Чтобы не отключать уж совсем

**Comment by jeefo** [comment]
Так в конечном итоге что нужно?

Чтоб в ShowMenu не передавалось текста?

**Comment by sergiopoverony** [comment]
Да чтобы не отображалось. Но работала при нажатии на кнопки. Просто чтобы
небыло отрисовки.

Это сообщение было отправлено с неинфицированного компьютера, защищенного
программой Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

30 января 2016 г., 15:30 пользователь jeefo <notifications@github.com>
написал:

**Comment by sergiopoverony** [comment]
Кстати вот заскринил двух баганутых. На одном сверху показывалось на другом нет
Спецнаовец  прыгал и крутился как в жопу ужаленный на месте. Террорист бегл туда - сюда. Потом вот в таком состоянии и завис. 
![screenshot_2016-01-30-00-14-55](https://cloud.githubusercontent.com/assets/5286127/12695404/e35f2ed0-c76e-11e5-8af6-7239cc756223.png)
![screenshot_2016-01-30-00-15-06](https://cloud.githubusercontent.com/assets/5286127/12695405/e362043e-c76e-11e5-83d5-30cabc6806c9.png)
![screenshot_2016-01-30-00-15-16](https://cloud.githubusercontent.com/assets/5286127/12695406/e362a358-c76e-11e5-9406-938d3880fc88.png)

**Comment by sergiopoverony** [comment]
![screenshot_2016-02-01-00-11-47](https://cloud.githubusercontent.com/assets/5286127/12704255/9efa511a-c878-11e5-9c37-c9bab9e17c67.png)
![screenshot_2016-02-01-00-11-11](https://cloud.githubusercontent.com/assets/5286127/12704260/ac7ed64e-c878-11e5-90d3-6610153eb0ab.png)

**Comment by sergiopoverony** [comment]
Вот так они и зависли

**Comment by jeefo** [comment]
Это происходит только когда у них гранаты в руках?

**Comment by sergiopoverony** [comment]
В больше степени да.
01 февр. 2016 г. 2:11 пользователь "jeefo" <notifications@github.com>
написал:

**Comment by jeefo** [comment]
Пофиксил вроде всё, включая меню. yb_display_menu_text нужно выставлять в 0 под андройдом, тогда текст отправляться не будет.
