### ISSUE TITLE
CT can't defuse the bomb planted at some places

### ISSUE THREAD

**Issue by kYov0** [jeefo/yapb#130]
Sorry for my poor English. I found that some C4 planted on the edge or the top of the boxes can't be defused correctly by CTs. CTs just walking around and ignoring the bomb. I'm using yapb 2.9.5395, official waypoint files, official steam cs (version 8308) and the problem happens on official de_dust2, de_nuke, de_inferno. This is really annoying and I want to know how to solve the problem.

**Comment by jeefo** [comment]
@kYov0 

Should be OK with: https://yapb.ru/files/release/4.0.0.443/
