### ISSUE TITLE
[Feature Request] Load .pwf that doesn't match mapname

### ISSUE THREAD

**Issue by APGRoboCop** [jeefo/yapb#132]
Privet/Hello. I'm trying to load that "de_aztec(cs 1.5).pwf" file for de_aztec_cs15.bsp map as that appears to have the waypoints that is needed for that map. But the problem is I must not rename that .pwf file as they contain a header that must match a particular mapname. So I thought on maybe using like "yapb wp load "de_aztec(cs 1.5).pwf" in de_aztec_cs15 map but that command for loading any other .pwf file doesn't exist.

I've noticed that those waypoints you got in yapb.ru appears to have various version for like de_aztec(11-15).pwf as well as de_aztec(cs 1.5).pwf both contain the "de_aztec" header as I assume those brackets are supposed to be removed for using YaPB for CS 1.5?

I've got some various version of de_aztec maps but contain suffixes to avoid confusion and to allow CS 1.6 server to load those older versions of de_aztec. Problem is I cannot load those waypoints with those brackets for de_aztec_cs15 unless it's possible for you to add like "yapb wp load <ANY-OTHER-MAP>.pwf" as I guess using "yapb wp load" will automatically load the matching mapname assigned for that .pwf file but will ignore any queries or that?

**Comment by Overitab** [comment]
bot use new format .graph waypoints that can be renamed
yapb\data\graph
just rename files, try find way that fits map , if not tell me what map i make for you new ways
