### ISSUE TITLE
Новая Версия Ботов Крашит игру !

### ISSUE THREAD

**Issue by Lolasik011** [jeefo/yapb#135]
Новая Версия Ботов Крашит игру !

**Comment by jeefo** [comment]
Информативно.

**Comment by jeefo** [comment]
Версия, игра, плагины.

**Comment by Lolasik011** [comment]
Cs 1.6 Steam , Cs 1.6 Condition Zero. Ось Windows 10. Версия ботов yaob-4.0.0-git443-windows

**Comment by Lolasik011** [comment]
> > Какая игра? Версия ботов? Какие плагины? Какая ОСь?
> > На hlds-linux, пока несколько суток без падений.
> 
> Cs 1.6 Steam , Cs 1.6 Condition Zero Steam. Ось Windows 10. Версия ботов yaob-4.0.0-git443-windows. Плагинов нету, чистые игры .

> P.S Старая версия работала нормально.

**Comment by jeefo** [comment]
Видимо без метамода крашит. Спасибо, проверю.

**Comment by jeefo** [comment]
можешь проверить: https://oshi.at/CmsRtn

этот билд крашится у тебя?

**Comment by Lolasik011** [comment]
@jeefo Все Равно Крашит :(

**Comment by jeefo** [comment]
Антивирусы есть?

**Comment by Lolasik011** [comment]
Нету

пт, 19 июн. 2020 г. в 00:00, jeefo <notifications@github.com>:

**Comment by Lolasik011** [comment]
@jeefo Нету

**Comment by jeefo** [comment]
А проц какой? Реально не могу поймать крэш у себя.

**Comment by Lolasik011** [comment]
I7 9700K

**Comment by Lolasik011** [comment]
> А проц какой? Реально не могу поймать крэш у себя.

**Comment by jeefo** [comment]
https://github.com/jeefo/yapb/releases/latest

Надо использовать виниловый инсталлятор.

**Comment by Lolasik011** [comment]
> https://github.com/jeefo/yapb/releases/latest
> 
> Надо использовать новый* инсталлятор.

Заработало !!! Спасибо Бро. 
У меня вопросик как русифицировать меню ботов ?
Я вродь в конфиге ru вписал но меню на Английском.

**Comment by jeefo** [comment]
Отлично!

Чуть позже поправлю. Там была куча оптимизаций. И мультистроковые данные пока не переводятся.

**Comment by jeefo** [comment]
Исравил в 419626d.

Билд зальется минут через 10 : https://github.com/jeefo/yapb/releases/latest
