### ISSUE TITLE
4.0.0 not stable

### ISSUE THREAD

**Issue by kYov0** [jeefo/yapb#136]
I'm using the default settings of yapb on steam cs and it always crashes. It crashes almost every time I play. I've tried official dust2, inferno, nuke, train. I also tried using metamod instead of the standalone version but the problem still exists.

**Comment by jeefo** [comment]
Hello.

https://yapb.ru/files/binaries/latest/debug/yapb.dll

Can you install debug  build, and send me crashdumpa from steam/dumps?

Related: #135

**Comment by jeefo** [comment]
https://github.com/jeefo/yapb/releases/latest

Should be OK.
