### ISSUE TITLE
No chat is visible when a player writes something

### ISSUE THREAD

**Issue by stambeto2006** [jeefo/yapb#138]
There is a problem with the chat when the yapb module is released.  The problem is that after a certain time when you write something in the chat and nothing is visible, it is as if you did not write anything in the chat itself.

**Comment by jeefo** [comment]
Hello. Can you please provide your server details. Plugins etc.

**Comment by stambeto2006** [comment]
> "module is released" - do u mean installed?

yes

**Comment by stambeto2006** [comment]
It's just that when you log in to the server with the bots running, after a certain time, when you type something in the chat, it doesn't look like you didn't write anything, but it is actually visible in the server console. This is only for the original steams!

**Comment by stambeto2006** [comment]
When I stop the yapb module, I don't have this chat problem!

**Comment by jeefo** [comment]
Can you provide server up?

**Comment by stambeto2006** [comment]
> Can you provide server ip?

Do you have steam? Send me your nick.

**Comment by jeefo** [comment]
Problem solved?
