### ISSUE TITLE
My CZero has become unstable

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#14]
After installing yapb, every time the bomb explodes, the game closes and I go back to Windows. 
Apparently yapb causes some sort of instability.

**Comment by jeefo** [comment]
Can you be more specific? What bot revision? Metamod or standalone? Official cs bots ingame?

I just played CZ a little. No crashes.

**Comment by leopard20** [comment]
I checked again and I'm positive. Without yapb the game works fine but after installation of yapb the game crashes when the bomb goes off.
And it doesn't matter if there are bots in game (yapb or original) or not. 
By the way, I played on de_dust 2 map and planted the bomb at bombsite B.

**Comment by leopard20** [comment]
One more thing, I installed yapb using the exe file that is available at the 'releases' section.

**Comment by jeefo** [comment]
It's doesn't matter. Steam?

Can you provide <steamdir>\dumps\crash_hl.exe*.dmp files?

**Comment by jeefo** [comment]
And try: https://yapb.jeefo.net/drop/releases/yapb_v2.7.2_win32_latest.exe

**Comment by leopard20** [comment]
I didn't find any file in my steam dir with .dmp format.
But there are a few files named sream_(some numbers).mdmp. Are they of any use to you?
I'll try the file that you provided and get back to you.

**Comment by jeefo** [comment]
.mdmp files should be OK.

**Comment by leopard20** [comment]
This is what I did in detail:
1) I removed condition zero completely from my computer. Then re-installed it.
2) Before installing yapb, I started a server (without bots), played 8 rounds and each round planted the bomb at B. The game didn't crash at all.
3) I installed yapb from the above link. Again I started a server, set the number of bots to zero. After the server started, I set yb_quota to 0. I played 4 rounds. The first 3 rounds were fine, but on the 4th round, the game crashed when the bomb went off. I started another server. This time the game crashed on the second round. Here is the link to the .mdmp files:

https://yadi.sk/d/ISK2-i8Anpyxn

**Comment by leopard20** [comment]
I forgot one thing. The map was de_dust 2.

**Comment by jeefo** [comment]
Ok. i have reproduced the problem. As a workaround you can install bot as metamod.

Will fix in some time.

**Comment by jeefo** [comment]
fixed in 8448bb3

**Comment by jeefo** [comment]
fixed in 8448bb3

**Comment by leopard20** [comment]
Where can I download the file? The latest update in the release section is from 25 days ago. Please upload the new version.

**Comment by jeefo** [comment]
here: https://yapb.jeefo.net/drop/releases/

**Comment by leopard20** [comment]
Are issues fixed in this release?

**Comment by jeefo** [comment]
Yep, but dirty.
