### ISSUE TITLE
yb_quota_mode "fill" + ping bot

### ISSUE THREAD

**Issue by chiken42380** [jeefo/yapb#141]
I have a ping problem it goes up to 200 see more
and I never have the number of bot 22 as indicated on the yapb.cfg
1 players connect 2 to 3 bot disconnect .. 

version bot installed yaob-4.0.0-git450-linux.tar.gz 

yb_quota_mode "fill"
yb_quota "22"

I tested all the bug version at home 

Ubuntu 18.04.4 LTS

4.0.0.443 
4.0.0.445 
4.0.0.446
4.0.0.447 
4.0.0.448 
4.0.0.449 
4.0.0.450

**Comment by jeefo** [comment]
Sorry, i din't actually get what your problems is.

Where do you see ping 200 ? In scoreboard ? or where? Whoes ping ? Players or bots? What will be if yb_latency_display is 0 ?

About quote_mode, what do you want to achieve ? and what you actually get ? I see no problems on test servers, which is running inside Docker at alpine linux, on Debian 10 host.

**Comment by chiken42380** [comment]
scoreboard  bot ping 200  no player my system ubuntu 18.04

**Comment by jeefo** [comment]
Bots do not have ping at  all, it's just fake digits.

What plugins do you use ?
