### ISSUE TITLE
Autokill bots

### ISSUE THREAD

**Issue by yuusuke09** [jeefo/yapb#143]
Autokillbot function often doesn't work after changing maps. 
Console may show up "All bots died...", but there is nothing happened whether I set autokill delay to 1.0 or use "end this round".
Hope that it can be fixed ASAP. Thank you.
(HLDS 8308 + AMXX 1.10.0.5402 + Metamod-P38 + Normal CStrike Mod)

**Comment by jeefo** [comment]
Hello. Bot version?

**Comment by jeefo** [comment]
Should be OK with 4.0.0.452, should be available in  https://github.com/jeefo/yapb/releases in 10 minutes.

Thank you for report.
