### ISSUE TITLE
Changes in bot AI don't take place immediately

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#15]
When I change certain things about bot AI, like difficulty or that yb_whose_your_daddy thing, they don't have any effect until first I kick the bots (yb_quota 0) and add them again. I know this isn't much of an issue but if changes take place immediately it will be better.

**Comment by jeefo** [comment]
yb_difficulty takes place only after kick-add action.

yb_whose_your_daddy - applied instantly.

Not a bug.
