### ISSUE TITLE
Bots being stucked in trying shooting breakables instead of going anywhere else

### ISSUE THREAD

**Issue by kYov0** [jeefo/yapb#156]
Bots sometimes keep trying shooting breakables but can't hit and they won't go anywhere because they can't break the breakables. Such as the wooden table in kitchen, de_mirage, the bots just try to aim at the table but they can only shoot at the floor under the table. So they just shoot at the floor instead of going anywhere else. Latest yapb (4.0.471), Steam CS.

**Comment by jeefo** [comment]
Hello.

Sitting right in front this table for a half hour)) No bots get stuck yet. Can you provide a screenshot ? (need to know bot position against the table).

**Comment by jeefo** [comment]
Try 4.0.172

**Comment by kYov0** [comment]
![20200913083320_1](https://user-images.githubusercontent.com/66195452/93007548-8bf4c900-f59c-11ea-855d-e229fb7ae57d.jpg)
![20200913083324_1](https://user-images.githubusercontent.com/66195452/93007549-8dbe8c80-f59c-11ea-805d-5e0409db18c7.jpg)
![20200913083330_1](https://user-images.githubusercontent.com/66195452/93007552-9020e680-f59c-11ea-9c0c-fc0533477233.jpg)
![20200913083333_1](https://user-images.githubusercontent.com/66195452/93007553-91521380-f59c-11ea-985d-f16339d47bce.jpg)

A bot stood here last time and aim at where I aim (Picture 4, the one that c4 has been planted).
This only happened for once.

It seems that in 4.0.472 bots won't be stucked in this anymore.

**Comment by jeefo** [comment]
Marking as fixed. If not, please reopen.
