### ISSUE TITLE
4.0.478 yapb.dll crash

### ISSUE THREAD

**Issue by yuusuke09** [jeefo/yapb#159]
hi, I just updated YAPB to 4.0.478, but the new yapb.dll crashed without any log. 

hlds 8684 + meta-p39 + amxx 1.10

**Comment by jeefo** [comment]
Hello. Thanks for report.

479 should be ready in a few minutes to download. It's contains fix.

**Comment by yuusuke09** [comment]
> 
> 
> Hello. Thanks for report.
> 
> 479 should be ready in a few minutes to download. It's contains fix. Can you test it?

Just tested it during 5 maps. 479 seems works good, and it hasn't crashed. thanks for fixing it.
