### ISSUE TITLE
Latency displayed is way to high.  yb_show_latency "2"

### ISSUE THREAD

**Issue by iclassdon** [jeefo/yapb#160]
Hello,  I am running an older build of yapb "2.9".   I started to test the new one and noticed that yb_show_latency "2" seems to be showing an average of overall server ping.   

On the older versions it doesn't seem to be doing that.  As it fluctuates very low around 40-50's  

Anyway to tweak this?  Looks more attractive for players to see low ping.   For instance in my case of testing the newer version, bots are displaying a ping of above 100msec. 

BTW thanks for this project it's excellent work!

**Comment by jeefo** [comment]
Hello. Try the latest one.

**Comment by iclassdon** [comment]
I loaded (480) and rebooted my server.  The latency displayed is perfect now but I get segment faults on map change.

> Dropped bisTEK from server
> Reason:  Dropping fakeclient on level change
> Successfully saved Bots Practice data.
> Bots are removed from server.
> Successfully saved Bots Practice data.
> Segmentation fault

**Comment by jeefo** [comment]
It's unlikely related. Test server is working perfectly with 480, with changeleveles to.

`Successfully saved Bots Practice data.`

Is repeated twice... Could you please provide `meta list`, and run server with `-debug` cmd to get crash backtrace?

**Comment by iclassdon** [comment]
Runs perfectly fine when I revert to older version no changes have been made since upgrading.  Here is the data I gathered below.

**Meta list results**
> Currently loaded plugins:
>       description   stat pend  file                      vers             src  load  unload
>  [ 1] AMX Mod X     RUN   -    amxmodx_mm_i386.so        v1.9.0.5247      ini  Start ANY  
>  [ 2] ReSemiclip    RUN   -    resemiclip_mm_i386.so     v2.3.9           ini  Chlvl ANY  
>  [ 3] YaPB          RUN   -    yapb.so                   v4.0             ini  Chlvl ANY  
>  [ 4] FakeMeta      RUN   -    fakemeta_amxx_i386.so     v1.9.0.5247      pl1  ANY   ANY  
>  [ 5] Ham Sandwich  RUN   -    hamsandwich_amxx_i386.so  v1.9.0.5247      pl1  ANY   ANY  
>  [ 6] ReAPI         RUN   -    reapi_amxx_i386.so        v5.12.0.192-dev  pl1  ANY   Never
>  [ 7] CStrike       RUN   -    cstrike_amxx_i386.so      v1.9.0.5247      pl1  ANY   ANY  
>  [ 8] CSX           RUN   -    csx_amxx_i386.so          v1.9.0.5247      pl1  ANY   ANY  
>  [ 9] Fun           RUN   -    fun_amxx_i386.so          v1.9.0.5247      pl1  ANY   ANY  
>  [10] Engine        RUN   -    engine_amxx_i386.so       v1.9.0.5247      pl1  ANY   ANY  
>  [11] ReCSDM        RUN   -    csdm_amxx_i386.so         v3.6             pl1  ANY   ANY  
> 11 plugins, 11 running

**What the console displayed**
> Successfully saved Bots Practice data.
> Segmentation fault (core dumped)
> BFD: Warning: /home/***/server/core is truncated: expected core file size >= 147623936, found: 2994176.
> Cannot access memory at address 0xf774f91c
> Cannot access memory at address 0xf774f918
> debug.cmds:1: Error in sourced command file:
> Cannot access memory at address 0xff9b11b8
> email debug.log to linux@valvesoftware.com


**debug.log**
> CRASH: Fri Sep 18 00:35:22 EDT 2020
> Start Line: ./hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.30839.pid
> [New LWP 30846]
> [New LWP 30847]
> [New LWP 30848]
> [New LWP 30850]
> [New LWP 30855]
> [New LWP 30856]
> [New LWP 30857]
> [New LWP 30858]
> [New LWP 30859]
> #0  0xf74cec83 in ?? ()
> End of crash report

**Comment by jeefo** [comment]
Older, you mean 2.9?

**Comment by iclassdon** [comment]
Yes, when running 2.9 it works fine.

**Comment by jeefo** [comment]
Strange.

https://bashupload.com/ZHYj1/yapb.so?download=1

This is debug binary. Can you replace original one, and run server again with `-debug` option?

**Comment by iclassdon** [comment]
Same results is there another form of logs you are looking to see? 

> Segmentation fault (core dumped)
> BFD: Warning: /home/***/server/core is truncated: expected core file size >= 145821696, found: 2994176.
> Cannot access memory at address 0xf77c491c
> Cannot access memory at address 0xf77c4918
> debug.cmds:1: Error in sourced command file:
> Cannot access memory at address 0xffd8fba8
> email debug.log to linux@valvesoftware.com
> Fri Sep 18 01:29:10 EDT 2020: Server restart in 10 seconds

> CRASH: Fri Sep 18 01:29:10 EDT 2020
> Start Line: ./hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.31900.pid
> [New LWP 31907]
> [New LWP 31909]
> [New LWP 31910]
> [New LWP 31912]
> [New LWP 31916]
> [New LWP 31917]
> [New LWP 31918]
> [New LWP 31919]
> [New LWP 31930]
> #0  0xf7543c83 in ?? ()
> End of crash report
> ----------------------------------------------

**Comment by jeefo** [comment]
well, if you have enough access and gdb installed on server)

Go to server dir and execute:
`export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"`

Run server via:
`gdb --args  ./hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.31900.pid`

When GDB started, pres `r` and `enter`.

Reproduce the crash. and then type `bt` to get correct callstack.

**Comment by iclassdon** [comment]
BTW this is the build of 2.9 that I had running before upgrading.  [YAPB] Bot v2.9.0.5395 Loaded. Game detected as Counter-Strike: v1.6 (BV) (SVC)

**Comment by iclassdon** [comment]
> 
> 
> well, if you have enough time and gdb installed on server)
> 
> Go to server dir and execute:
> `export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"`
> 
> Run server via:
> `gdb --args ./hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.31900.pid`
> 
> When GDB started, pres `r` and `enter`.
> 
> Reproduce the crash. and then type `bt` to get correct callstack.

Yes,  I have root access.  I'll give that a try.

**Comment by iclassdon** [comment]
Is there a log file that I should be looking for? This is what my console displays. I didn't find any new logs file in the server folder. 

> gdb --args ./hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.31900.pid
> GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from ./hlds_linux...(no debugging symbols found)...done.
> (gdb) r
> Starting program: /home/****/server/hlds_linux -debug -game cstrike +sys_ticrate 1000 -pingboost 2 -port 27015 -secure +maxplayers 32 +map awp_india -pidfile hlds.31900.pid
> Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error
> warning: File "/lib/i386-linux-gnu/i686/cmov/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
> To enable execution of this file add
>         add-auto-load-safe-path /lib/i386-linux-gnu/i686/cmov/libthread_db-1.0.so
> line to your configuration file "/root/.gdbinit".
> To completely disable this security protection add
>         set auto-load safe-path /
> line to your configuration file "/root/.gdbinit".
> For more information about this security protection see the
> "Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
>         info "(gdb)Auto-loading safe path"
> 

> Successfully saved Bots Practice data.
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0xf7d7cc83 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
> (gdb)

**Comment by jeefo** [comment]
Thank you. Not useful for some reason.

Could you please gzip entire addons folder and hlds files (hlds_linux, engine_i486.so, hlds_run). Strip passwords from amxx (you can delete users.ini amxmodx.cfg and so on). and give the link to archive ? ds@stx.su If privately.

**Comment by jeefo** [comment]
> BTW this is the build of 2.9 that I had running before upgrading.
> 
> > [YAPB] Bot v2.9.0.5395 Loaded. Game detected as Counter-Strike: v1.6 (BV) (SVC)

this won't help actually, there are too much changes to compare...

**Comment by iclassdon** [comment]
I'll provide the link in a bit.

**Comment by iclassdon** [comment]
I sent it over via dropbox.

**Comment by jeefo** [comment]
Received...
welll

```
CPU   In    Out   Uptime  Users   FPS    Players
 6.20  0.00  0.00     658   468  896.57       0

```
30 mapchanges, without crash.

Could you please provide CPU & OS version ?

**Comment by iclassdon** [comment]
Single core 3.4ghz cpu
Debian 7.8 64bits

I am going to upgrade to the latest debian which is v10.  Possibly outdated libs causing the segment faults.   

"0xf7d7cc83 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6"  <~~~ may be the clue.  

I'll get back to you shortly sorting things out with host.

**Comment by jeefo** [comment]
and what is cpu vendor model ?

**Comment by jeefo** [comment]
> Single core 3.4ghz cpu
> Debian 7.8 64bits
> 
> I am going to upgrade to the latest debian which is v10. Possibly outdated libs causing the segment faults.
> 
> "0xf7d7cc83 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6" <~~~ may be the clue.
> 
> I'll get back to you shortly sorting things out with host.

Outdated libs shouldn't cause segfaults.

**Comment by iclassdon** [comment]
I know it was an intel using kvm hypervisor so I don't have specific cpu info.

**Comment by jeefo** [comment]
Ok, i have setup test VM Debian 7.11 x64 with you server setup on KVM hypervisor and tested with CPU=kvm64 & CPU=host.

Tested on hosts with
 * Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz
 * ntel(R) Xeon(R) CPU X5680 @ 3.33GHz
 * Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz

they all run your setup just fine in both KVM & HOST cpu settings in hypervisor. If you're still run into the problems. 

Can you please provide SSH access with ability to run HLDS to debug.

**Comment by jeefo** [comment]
closed as stale.
