### ISSUE TITLE
Assign valve id to bots

### ISSUE THREAD

**Issue by xpt1x** [jeefo/yapb#163]
I want bots to have unique valve ids for bots too 
Theres a cvar for faking bot query but its useless if BOT status is publically visible in status cmd

I am using REHLDS 
Similar to #52

**Comment by jeefo** [comment]
Hello. It's needs patching for ReHLDS.

Is it worth? I mean, it's relatively easy to know if there's bots playing on server, atleast by looking at them)

If really needed, i can provide "patched" rehlds binary. But idk, if i can to continue support this patch. As it will be not be merged with upstream.

**Comment by xpt1x** [comment]
@jeefo  Can your provide the patched repo or zip ( i mean the source ) i will support it myself with later versions

**Comment by jeefo** [comment]
OK. I hope i will have some  time by the end of this week to apply patches.

**Comment by jeefo** [comment]
closed as stale.
