### ISSUE TITLE
meson компиляция

### ISSUE THREAD

**Issue by vladislav980** [jeefo/yapb#165]
Привет и всего хорошего, а так же спасибо за ботов =)
Хотел бы узнать что не так!?
В общем компилирую ботов через meson у меня они работают на сервер под linux wsl2 
Но когда скидываю другу, у него они не работают.
Вот что пишет у него в консоли сервера
 <yapb.so> badf load yapb.so
meta info yabp.so
Couldn't find plugin matching 'yabp.so'
Но когда я в meson.build меняю c 'buildtype=release', на 'buildtype=debug', то они у него работаю ну и файл весит 10мб
Может нужно как-то по особенному компилировать а не двумя командами?)

**Comment by jeefo** [comment]
Привет. Друг случаем не на kvm запускает сервер?

**Comment by wopox1337** [comment]
Можно попробовать использовать статическую линковку

**Comment by jeefo** [comment]
> Можно попробовать использовать статическую линковку

Там скорее включение SSE3 дает такой эффект, meson собирает с флагом ``default_library=static``. libstdc++ вообще запрещен, и бот не требует линковки с ним. 

Протухший glibc на тачке тоже врядли, ибо отладочный билд запускается.

@vladislav980  попробуй скомпилить послений коммит.

**Comment by vladislav980** [comment]
вот что в этот раз
meta info yapb
name: (nil)
desc: <yapb.so>
status: badfile
action: load
filename: addons/yapb/bin/yapb.so
file: yapb.so
pathname: /home/srv491903/cstrike/addons/yapb/bin/yapb.so
index: 17
source: ini file
loadable: -
unloadable: -
version: (nil)
date: (nil)
author: (nil)
url: (nil)
logtag: (nil)
ifvers: (nil)
last loaded: Thu Jan 1 03:00:00 1970
No DLLAPI functions.
No DLLAPI Post functions.
No NEWAPI functions.
No NEWAPI Post functions.
No Engine functions.
No Engine Post functions.
Registered commands:
0 commands
Registered cvars: float value string value
0 cvars
No child plugins.

**Comment by vladislav980** [comment]
Самое интересно что если брать уже готовых от сюда то они у него работаю.

**Comment by jeefo** [comment]
А если взять не делфолтную, а:

https://yapb.ru/files/binaries/4.0.486/release/

yapb.clang.so
yapb.gcc.so

они тоже у него заработают?

По умолчанию комплияцию выполняет intel c++ compiler.

**Comment by vladislav980** [comment]
Я компилирую на amd, может в этом и есть причина. Позже отпишусь работает ли у него.

**Comment by jeefo** [comment]
скомпилил на Ryzen 3600X на WSL2. Работает на тестовых машинах)

ldd yapb.so что у него кажет?

**Comment by vladislav980** [comment]
У него на хостинге нет доступа к консоли, ток консоль сервера.

**Comment by jeefo** [comment]
А какой хостинг?

**Comment by vladislav980** [comment]
хостинг csserv
yapb.clang.so запустился
yapb.gcc.so не работает

**Comment by vladislav980** [comment]
~/yapb-master$ CC=clang CXX=clang++ meson build-clang
The Meson build system
Version: 0.55.3
Source dir: /yapb-master
Build dir: /yapb-master/build-clang
Build type: native build
Project name: yapb
Project version: 4.0
Using 'CXX' from environment with value: 'clang++'
Using 'CXX' from environment with value: 'clang++'
C++ compiler for the host machine: clang++ (clang 9.0.1-14 "clang version 9.0.1-14 ")
C++ linker for the host machine: clang++ ld.bfd 2.35
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program ninja found: YES
Program git found: YES
Program hostname found: YES
Configuring version.build.h using configuration
Program lld found: YES
Build targets in project: 1

Found ninja-1.10.1 at /usr/bin/ninja

~/yapb-master/build-clang$ meson compile

Found runner: ['/usr/bin/ninja']
ninja: Entering directory `.'
[14/14] Linking target yapb.so

Хотел бы узнать так ли я делаю и обязательно ли нужна lld? Просто в первый раз без него компилировал.

**Comment by vladislav980** [comment]
Скинул друг, боты работаю что с lld что без, но оставил с lld.

**Comment by jeefo** [comment]
с GCC и флагом -flto не запускается на некоторых серваках, попробовал на майарене.

Пока выключил в meson.build, GCCшные бинарники должны тоже заработать.

**Comment by vladislav980** [comment]
Скомпилировал, скинул, работают. Спасибо =) А есть ли разница gcc и clang?

**Comment by jeefo** [comment]
В пределах погрешности. Как и Intel'ом.

В общем в принципе разницы нет.

**Comment by vladislav980** [comment]
Странно на одном сервере все в порядке а на другом 1 бот создается а остальных кикает, ну наверно это уже связанно с самой сборкой. в мета инфо квары по 0 в yb_quota, yb_uqota_match будто не считывают конфиг. Нипонятно но очень интересно =)

**Comment by vladislav980** [comment]
В общем если на сервере 5 игроков то боты вообщ не создаются. А при долгом создание начинает писать что 10/10 создано :D

**Comment by vladislav980** [comment]
Хотя при компиляции clang работало. Эх, уж этот секс)

**Comment by vladislav980** [comment]
а теперь работает, создались нормально и кикает при подключении игрока.
