### ISSUE TITLE
CS skin request

### ISSUE THREAD

**Issue by kYov0** [jeefo/yapb#166]
Can I specify all bots the default skin of all bots, such as all T bots choose l337 and all CT bots choose gign? Some skins are really difficult to recognize in some maps.

**Comment by jeefo** [comment]
Hello.

It's needed per-team ? Or just introduce single yb_botskin cvar  with 1-4[5 for cz] range ?

**Comment by kYov0** [comment]
What I wish is per-team.Thank you.

**Comment by jeefo** [comment]
Should be working in latest build.
