### ISSUE TITLE
Updated YaPB documentation

### ISSUE THREAD

**Issue by Vladislav4KZ** [jeefo/yapb#167]
Hi I have updated the official YaPB documentation (for readthedocs.io). It is relevant at the time of the release of the latest version of the bot. (4.0.485)

Added descriptions of new cvars and commands, deleted old ones. Added additional sections. Added new pictures.

You can find it here: https://gitlab.com/S_Vladislav/yapb-docs

I will make a Russian version of the documentation soon.

**Comment by jeefo** [comment]
hi!
wow!

thank you a bit! i really have hard time supporting the docs... 

can i do following: https://github.com/yapb/docs and give you the access to this repo ?

**Comment by Vladislav4KZ** [comment]
> can i do following: https://github.com/yapb/docs and give you the access to this repo ? 
> 
> https://docs.yapb.ru/
> 

Sure, I will try to support it.


> One thing. if possible. Any  change to get light theme? :(
> 
> 

Remove rtd_dark.css from conf.py
