### ISSUE TITLE
YaPB always tries to download graph file in lower case.

### ISSUE THREAD

**Issue by Vladislav4KZ** [jeefo/yapb#174]
Map: cs_KVARTAL2
File in graph database: cs_KVARTAL2.graph (in upper case)

The following error appears in the game:
Unable to download cs_kvartal2.graph from http://yapb.ru/graph/cs_kvartal2.graph

**Comment by jeefo** [comment]
Changed all graph files in DB to lowercase.

Saving will all lowercase too (and uploading). A little later.

**Comment by jeefo** [comment]
Should be fixed in latest revision.
