### ISSUE TITLE
Получение id команды(CT/T) энтити других игроков.

### ISSUE THREAD

**Issue by vladislav980** [jeefo/yapb#175]
Можно ли сделать что бы боты понимали в чьей команде находится созданная игроком/ботом энтити?

**Comment by jeefo** [comment]
Наверное можно, что боты должны с этой информацией делать?)

**Comment by vladislav980** [comment]
Ну тут уж можно много чего себе загадать и на выдумывать :D Ну такое простое к примеру взять самый доступный sentry gun by Johnny got his gun и что бы боты реагировали на свое/чужое ) Ну не знаю стреляли к примеру в них или избегал в общем фантазии ого-го(ну не удивительно) а вот реализовать ее надо более менее какое-то знание.

**Comment by vladislav980** [comment]
а вот к примеру о чем подумал, можно ли таким способом получить команду игроков: int sentrygun = ent->v.iuser2;?
в Amxx это 
#define SENTRY_INT_TEAM			EV_INT_iuser2

**Comment by vladislav980** [comment]
Хотя че спрашивать пойду методом девственного тыка проверю :D

**Comment by vladislav980** [comment]
В общем получилось, но в CS: T = 1,  CT = 2  а у ботов Terrorist = 0 а  CT = 1 если сравнивать с m_team

**Comment by vladislav980** [comment]
Это выйдет надо делать так?:
int sentrygun = ent->v.iuser2;
 if (sentrygun == 1) {
          sentrygun = 0;
      }
      else if (sentrygun == 2) {
          sentrygun = 1;
      }
что бы потом составить условие если и m_team == sentrygun;

**Comment by vladislav980** [comment]
и сравнивать это по класснейму?

**Comment by jeefo** [comment]
Если надо чтоб боты атаковали такие энтити, это можно сделать. Но, увы, потребует неплохо отрефакторить код. Враги сейчас, только игроки.

**Comment by vladislav980** [comment]
самое простое на что ума хватило а его не много, это боты реагируют на пушки своей команды и подходят их прокачивают или подходят к раздатчику и пополняют хп. И потом идут как всегда по своим делам:D

**Comment by vladislav980** [comment]
А, точно, решен вопрос, чет забыл закрыть =)
