### ISSUE TITLE
Server crashes on yb cvars command

### ISSUE THREAD

**Issue by Vladislav4KZ** [jeefo/yapb#176]
Latest YaPB release 4.0.499 (English Language)
When entering the command "yb cvars", the server crashes with this error:
Host_Error: PF_MessageEnd_I:  Refusing to send user message TextMsg of 258 bytes to client, user message size limit is 192 bytes

In Russian language, a similar problem which was not there before

**Comment by Vladislav4KZ** [comment]
By the way, there is no such problem on a dedicated server. This is only on the listen server.

**Comment by jeefo** [comment]
Can you please verify with https://github.com/jeefo/yapb/commit/fba383752309ad5e6cfbc696c61473f594922e81

**Comment by jeefo** [comment]
`yb g clean all` should not cause any problems too. With listen or dedicated / server.
