### ISSUE TITLE
OUT OF MEMORY

### ISSUE THREAD

**Issue by sourcepowered** [jeefo/yapb#178]
ReHLDS + ReGameDLL + Metamod-R + AMX Mod X 1.9.5271 + Yapb 4.0.501, it crashed after about 30 minutes after turning on the server, and take a messagebox "OUT OF MEMORY". What?! Can't I run the server for a long time? The old version 2.0 does not have this problem, and the server will not be like this after 10 consecutive days.

**Comment by jeefo** [comment]
Map ? Hosting?

**Comment by sourcepowered** [comment]
Map: Random, automatic switching every 30 minutes, but just official map.
Game Mode: Just Official Mode.
No, I installed 4.0.501 directly without upgrading from any version.
The server is the Steam version, Not NO-Steam.

**Comment by jeefo** [comment]
Just tested same setup, but on a VM @ Azure. but with Windows 2019...

] stats
CPU   In    Out   Uptime  Users   FPS    Players
 1.04  0.00  0.00     158   414  999.56       0

Running pretty nice... so far, with 2 and half hour. Could you put up your addons folder (stripping passwords) into zip and send to link dmitry@jeefo.net. As i can't reproduce with my setup.

BTW, is that a VPS ? How much memory dedicated to VM?

**Comment by jeefo** [comment]
closed as stale.
