### ISSUE TITLE
PODbot waypoint compatibility dropped?

### ISSUE THREAD

**Issue by ViBE-HU** [jeefo/yapb#179]
It's been a long time since I thoroughly followed the development and I don't know what kind of changes happened. Does the new versions still supports waypoint or not anymore?

**Comment by jeefo** [comment]
They still supported. Need to put into data/pwf dir. Also you can save them in old format, if waypoint count < 1024 with `yb g save oldformat`.

**Comment by ViBE-HU** [comment]
Ah, okay. Cause I thought it dropped and replaced with the graph. So if I have old .pwf files it will load automatically as usual?

**Comment by regener** [comment]
He meant the folder for old format inside yapb:
`addons/yapb/data/pwf`

**Comment by ViBE-HU** [comment]
My bad. Mixed but. Thanks.
