### ISSUE TITLE
Let there be peace

### ISSUE THREAD

**Issue by regener** [jeefo/yapb#180]
A cvar would be nice to make the bots peaceful (alias notarget), so I can test objectives without bots killing each other.

**Comment by jeefo** [comment]
https://docs.yapb.ru/en/latest/configuring.html#yb-ignore-enemies ?

**Comment by regener** [comment]
Wow, so there is a Doc? I didn't even know that. 😄
You should include that inside the About part.

Also thanks for the answer.
