### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by jaythomas77** [jeefo/yapb#182]
1) I had added 15 Bots in Server.
when mp_auto_join_team was 1
All bots were in spectator teams. They Could'nt join CT/T.
-------------------------------------------
2) Everytime there is 1 bot who stays in spec.
-------------------------------------------
3) Bots are still camping and shift walking when 
yb_camping_allowed "0"
yb_graph_fixcamp "0"
yb_walking_allowed "0"
-------------------------------------------
4) Bots using other weapons where I have only enabled deagle,ak,m4,awp
yb_restricted_weapons "usp;glock;p228;elite;fn57;m3;xm1014;mp5;tmp;p90;mac10;ump45;galil;famas;sg552;aug;scout;g3sg1;sg550;m249;flash;sgren;defuser;shield"
-------------------------------------------
5) Compiled tweaked rehlds from 
https://git.stx.su/ds/rehlds-fbs/commit/75c055267c7d5c0ac49bd2ced82922251249d6be
So that BOTs can get Nonsteam/Valveid
But its not working
-------------------------------------------
6) In server browser total player count is = bot in spec + actual Players.
Other bots who have joined team aren't showing in Server Browser.
yb_enable_query_hook "1"
![steambrowser](https://user-images.githubusercontent.com/58573008/97099537-18240100-16b0-11eb-8677-ed02392f89ec.jpg)
![ingame](https://user-images.githubusercontent.com/58573008/97099542-1d814b80-16b0-11eb-917b-686aab0c07ba.jpg)

-------------------------------------------
7) BOTs dont have their own Playtime? Like If I change Bot quota from 15 to 20 in middle, the new bots joined also have the same time as the old ones
-------------------------------------------
8) When a BOT is kicked from console, The new BOT which Joins in place of that has the same playtime

**Comment by jeefo** [comment]
one problem = one issue.
