### ISSUE TITLE
Waypoint Flag request: knife / melee (depending on mod)

### ISSUE THREAD

**Issue by regener** [jeefo/yapb#183]
A knife or melee Flag would be useful for waypoints.
For example we can make knife only zones (like the bridge on awp_india), because the bots still shoot there.
*I have a plugin that makes weapon damage to 0 on the bridge, but bots doesn't start to knife anyone, but just keep shooting pointlessly.*

**Comment by jeefo** [comment]
Hello. Let's track this with https://github.com/jeefo/yapb/issues/191  as it's probably better to do with some kind of API, instead of adding custom waypoint flags.
