### ISSUE TITLE
YaPB can't load pwf waypoints

### ISSUE THREAD

**Issue by Vladislav4KZ** [jeefo/yapb#192]
It started with the version where the "pwf" folder was created for old waypoints.

It also couldn't load pwf from "data" directory

Clearing the yb_graph_url cvar doesn't help

**Comment by jeefo** [comment]
Not sure, they're unable to load from ``yapb/data/pwf`` directory or from the ``yapb/data`` directory ?

**Comment by Vladislav4KZ** [comment]
False alarm, possibly damaged or very old waypoint. Checked the rest, they load successfully
