### ISSUE TITLE
Bot don't buy

### ISSUE THREAD

**Issue by ThePhoenixd** [jeefo/yapb#194]
Я писал автору, что боты не закупаются и да у меня сервер отличается от других и я подрубаю временами ботам csdm режим, но отключив все плагины, оставив только admin_loader боты сказали тоже самое. что и с плагинами.

https://dropmefiles.com/fVlby - видео с моментами попыток переключения кваров и т.д.
Позже решил загрузить и команды с консоли во время снятия видео - https://dropmefiles.com/so5IS

> amxx 1.9.0.5271
> rehlds 5.18.0.474-dev
> regamedll 5.18.0.474-dev
> Metamod-r v1.3.0.128

```
Currently loaded plugins:
      description      stat pend  file                        vers             src  load  unload
 [ 1] Reunion          RUN   -    reunion_mm_i386.so          v0.1.0.92c       ini  Start Never
 [ 2] Rechecker        RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY  
 [ 3] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC5         ini  ANY   ANY  
 [ 4] SafeNameAndChat  RUN   -    SafeNameAndChat.so          v1.1             ini  ANY   ANY  
 [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5271      ini  Start ANY  
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.696         ini  Chlvl ANY  
 [ 7] ReSemiclip       RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY  
 [ 8] YaPB             RUN   -    yapb.so                     v4.0.499         ini  Chlvl ANY  
 [ 9] MySQL            RUN   -    mysql_amxx_i386.so          v1.9.0.5271      pl5  ANY   ANY  
 [10] ReAPI            RUN   -    reapi_amxx_i386.so          v5.15.0.197-dev  pl5  ANY   Never
 [11] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl5  ANY   Never
 [12] Admins Kit       RUN   -    adminskit_amxx_i386.so      v1.0.2           pl5  ANY   Never
 [13] GeoIP            RUN   -    geoip_amxx_i386.so          v1.9.0.5271      pl5  ANY   ANY  
 [14] FakeMeta         RUN   -    fakemeta_amxx_i386.so       v1.9.0.5271      pl5  ANY   ANY  
 [15] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5271      pl5  ANY   ANY  
 [16] CStrike          RUN   -    cstrike_amxx_i386.so        v1.9.0.5271      pl5  ANY   ANY  
 [17] Engine           RUN   -    engine_amxx_i386.so         v1.9.0.5271      pl5  ANY   ANY  
 [18] Fun              RUN   -    fun_amxx_i386.so            v1.9.0.5271      pl5  ANY   ANY  
18 plugins, 18 running
```

**Comment by ThePhoenixd** [comment]
https://dropmefiles.com/iDLWl - забыл залить конфиги ботов. Перед тестом я залил дефолтные, кроме главного yapb.cfg

**Comment by jeefo** [comment]
amxx plugins?

**Comment by ThePhoenixd** [comment]
Как я и сказал тест проводился с одним admin_loader.amxx
Так что, они никак повлиять на процесс не могут.

**Comment by ThePhoenixd** [comment]
Можно закрывать, т.к вроде исправил. Проблема в yb_csdm_mode. Но что именно, я не знаю. Переприсваивал значение конфигом для режима и боты как наотрез отказывались закупаться при смене на классический!
Хотя сравнивания кварлист ДО (когда боты закупаются) и ПОСЛЕ (когда уже НЕ закупаются) - разницы 0, всё идентично.

**Comment by jeefo** [comment]
А как настраивал?

Должно быть так:
https://docs.yapb.ru/en/latest/configuring.html#yb-csdm-mode

**Comment by ThePhoenixd** [comment]
по дефолту стоит 0, при надобности устанавливался в 2
Как вариант можно было бы попробовать устанавливать в 3 по дефолту, конечно.

**Comment by jeefo** [comment]
Надо сделать ремарку. Что автодетект работает только на официальном csdm от
alliedmods.

Остальные (recsdm и прочее) не регистрируют csdm_active квар.

**Comment by ThePhoenixd** [comment]
Всё правильно. То есть по сути он должен отключать ксдм режим, на что я и рассчитывал, но видимо зря)

**Comment by jeefo** [comment]
А какое значение mp_freeforall при этом?

**Comment by ThePhoenixd** [comment]
Честно говоря, не в курсе, потому что проверял только по совпадению "yb_", но в теории, regamedll должен был выставить 0.

**Comment by jeefo** [comment]
Будем считать, что лучше рулить этим кваром в ручную, исходя из режима сервера.
