### ISSUE TITLE
Bad spawning

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#20]
Sometimes bots get stuck into each other,and (I think) sometimes they are spawned into the ground because I see the bots, but I can't shoot them; the bullet passes right through them. 
I played on de_dust cz, and it happened at CT spawn.
But it happens randomly.

**Comment by leopard20** [comment]
After playing for a little longer, I noticed it happens at T spawn too. Screenshot:
![untitled](https://cloud.githubusercontent.com/assets/16115820/12699129/c5cdc53c-c7c5-11e5-9c0e-fc1b7f95bc52.jpg)

**Comment by leopard20** [comment]
As you can see the CT bot is firing at the stuck T bots, but they don't die.

**Comment by jeefo** [comment]
Only cz affected?

**Comment by leopard20** [comment]
No. The same thing goes for CS1.6 (the cstrike folder in the same directory az czero).
![2016-02-01-0210-22 2016-02-01-02-11-51](https://cloud.githubusercontent.com/assets/16115820/12705573/5fe6c632-c889-11e5-98f4-b5f5c9ebb849.JPG)
Note that the stuck bots aren't completely frozen. Their bodies move as if they're breathing.

**Comment by leopard20** [comment]
> Do you think it's because I set the number of bots (yb_quota 33) to more than the server's allowance, which is 32 players (which means, setting me aside, the number of bots should be 31)?
Nope
I set yb_quota to 31 this time, but the same thing still happens

**Comment by jeefo** [comment]
should be fixed in latest rev.
