### ISSUE TITLE
Bots keep saying 'negative'

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#21]
Bots send the 'negative' radio command repeatedly (almost all of them), as if they think I'm saying 'follow me'. It happens even when I'm not close to them. 
This issue happened only once though, when I set yb_quota to 0 and then reset it to 33! And by the way, I didn't move from the spawning site. I think it happened when my 'follower' was killed.

**Comment by jeefo** [comment]
Should be fixed in latest rev.
