### ISSUE TITLE
CT bots don't report where the bomb is

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#28]
When a bot notices that a bomb site is clear, they should send the 'sector clear' message (with chatter activated, they should say, for example, 'A, clear'), and when they are close to the bombed site, they should say 'the bomb's at ....'. If you play with the original bots, you'll know what I mean.

**Comment by leopard20** [comment]
It's not just the bomb site they don't report. They don't report when they see the enemy (they should say where the enemy is, like 'side door'), when they see the bomber (by saying 'I see the bomber/he's got the package', etc), or when CTs are taking the hostages. 
I think your bots are kinda shy! Gotta teach 'em to talk more! ;-)

**Comment by jeefo** [comment]
Well, with chatter it's not possible, as YaPb doesn't know places names.

**Comment by leopard20** [comment]
Can't you add it to YaPb?
