### ISSUE TITLE
Please add how-to install in readme

### ISSUE THREAD

**Issue by jenshandersson** [jeefo/yapb#3]
Would love if you could write how to install this, especially for mac and steam.

**Comment by jenshandersson** [comment]
I managed to get it working after some trial and error, could be useful to put this on the readme for others.

Download latest release here: http://forums.bots-united.com/showthread.php?t=9986

Install for Mac
1. Download latest mac osx release
2. Locate your cstrike folder (eg. /Users/<user>/Library/Application Support/Steam/steamapps/common/Half-Life/cstrike)
3. copy the newly downloaded 'addons' folder to your cstrike folder
4. edit liblist.gam, change `gamedll_osx "dlls/cs.dylib"` to `gamedll_osx "addons/yapb/bin/yapb.dylib"`

**Comment by leopard20** [comment]
I know this is not the place, but what is exactly POD bot? Are they offline bots for CS? Does it work with the soon-to-be-released CS 1.6 android? Also, do the bots have adjustable difficulty level?

**Comment by leopard20** [comment]
I know this is not the place, but what exactly is POD bot? Does it generate offline bots for CS? Does it work with the soon-to-be-released CS1.6 android? Do the bots have adjustable difficulty level?

**Comment by jeefo** [comment]
Hi! better late than never :)

https://yapb.readthedocs.io/en/latest/installation.html#installing-bot-on-mac-os-x
