### ISSUE TITLE
Again some goal priority issue

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#31]
The priority issue isn't completely solved. Bots are still distracted by the enemy. For example, there was this time when a CT bot was about to go and defuse the bomb, when he saw a T bot running away. And instead of defusing the bomb, the CT bot went after the T bot.

**Comment by jeefo** [comment]
Can you test te latest build ?

**Comment by leopard20** [comment]
I was playing using the latest build. Have you updated the file since last week?

**Comment by jeefo** [comment]
https://yapb.jeefo.net/drop/releases/

**Comment by jeefo** [comment]
Any news?

**Comment by leopard20** [comment]
Hi buddy. 
Sorry I was quite busy the last few weeks; didn't really have time to test the latest build.
The issue still persists based on my experience. Maybe I should tell you exactly what happened:
I was playing on map de_dust 2. A CT bot was passing through CT spawn to go defuse the bomb that was planted at A. Then a T bot turned up  behind him from double doors and started shooting. Then the CT bot went after the T bot instead of going after the bomb.

**Comment by jeefo** [comment]
It's should be better now. Still not perfect.

**Comment by leopard20** [comment]
@jeefo Thanks a lot.
