### ISSUE TITLE
cant find download for 2.73 

### ISSUE THREAD

**Issue by vase070** [jeefo/yapb#37]
i can not find a working download for 2.73 anywhere, on the releases section there is only source code download for 2.73 pls fix also all these links don't work anymore 

http://forums.bots-united.com/showthread.php?t=9986

p.s : only the waypoints links work

**Comment by jeefo** [comment]
Yeah sorry.

Will fix all the links tomorrow.

**Comment by jeefo** [comment]
Links fixed. Sorry for the delay.

Available here: https://yapb.ru/files/releases/2.7/
