### ISSUE TITLE
bots can't join a game

### ISSUE THREAD

**Issue by Vaqtincha** [jeefo/yapb#39]
Regamedll build: 0.2.156
yb_version: 2.8.4659
CVars:
mp_auto_join_team 0
yapb.cfg (default)

**Comment by jeefo** [comment]
```
mp_auto_join_team
"mp_auto_join_team" is "0"
yb_version
"yb_version" is "2.8.4666"
game_version
"game_version" is "0.2.156"
sv_version
"sv_version" is "1.1.2.7/Stdio,48,921"
```
4666 has no changes regarding team joining from 4659.

here test server with latest yapb, rehlds, regamedll @ 1000fps:
`145.255.234.228:28000 `
