### ISSUE TITLE
"Follow me" periodical bot spam

### ISSUE THREAD

**Issue by Fixer-007** [jeefo/yapb#48]
At middle and end of the round when few bots left, certain bot starts spamming "Follow me" (and possibly others) radio message every N seconds over and over again, mostly during camping, with some pauses between spam.
Can be observed on cs_mansion (waypoints by BoBa Komato3nik), game with 17 bots + player as T.

```
] version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 13:14:12 Aug 29 2013 (6153)
] yapb version
------------------------------------------------
Name: Yet Another POD-Bot
Version: 2.8 (Build: 4766)
Compiled: Feb  6 2017, 19:37:18
Git Hash: 2ec5a730b0dbd792e7dec41b8a7a94771a3f477f
Git Commit Author: dmitry@jeefo.net
------------------------------------------------
```

**Comment by jeefo** [comment]
Confirmed. We'll look into this next week.

**Comment by Fixer-007** [comment]
Many weeks passed, have you looked into it? It is quite annoying bug :(

**Comment by jeefo** [comment]
Wel'' release update this weekend.

**Comment by Fixer-007** [comment]
Tested with 2.9 on cs_coldmansion, still happens, with mostly repeating messages "Regroup team", "Follow me", etc three or more times, but they do shut up this time, happens every round.

**Comment by Fixer-007** [comment]
Radiochat is very quite after this change, with very rare radio messages.

**Comment by VladAndroidGamer** [comment]
I installed the latest version YaPB with latest binary 2.9.5406. And the bots will no longer send spam messages "Follow me." It happens that says "Taking Fire, Need Assistance" 3 times. And that's all.

**Comment by Overitab** [comment]
Чутка потестил последнюю 5465 версию, вроде теперь войс чат не спамит .
Можно добавить ботам закупку гренами в конце раунда на карте fy_iceworld и чтоб вначале следующего раунда закидывали сразу же?
Баланс сложности по-моему сместился , уже 3 левел ботов слишком сильно лупит

**Comment by Overitab** [comment]
хотел проверить как боты кидают грены, на карте he_tennis стреляют через стекло. Может убрать вообще стрельбу с he карт? На карте he_dodgeball только пару раз кинули грены, в основном режут ножами ))  На карте he_glass боты так же не кидают грены. Вот пути отредактированные. 
https://cloud.mail.ru/public/6D2i/BrgyJardu
Наверное надо добавить для таких карт поиск ближайшей грены и сразу же её запуск в сторону противника.

**Comment by jeefo** [comment]
C гренами все сложно. Чтобы их кинуть нужно сделать много просчетов.

Не уверен, что будет возможность заставить пользоваться только ими...)

**Comment by jeefo** [comment]
По поводу спама хз)) надо опять смотреть.

**Comment by VladAndroidGamer** [comment]
В YaPB 2.9 build 5503 боты не спамят. Только что играл с ними. Теперь всё как надо, один раз сказали и всё
