### ISSUE TITLE
"yb_listenserver_welcome" cvar removed?

### ISSUE THREAD

**Issue by GoDhAnD-897** [jeefo/yapb#49]
Why was this cvar removed? I found it useful because the message annoy me after a while.
I compared the support.cpp at the top of the CheckWelcomeMessage() function.

version 2.7.2:
`static bool alreadyReceived = !yb_listenserver_welcome.GetBool ();`

since v2.73 its just:
`static bool alreadyReceived = false;`

the yapb.cfg contains this cvar in all versions.

**Comment by jeefo** [comment]
If it's something that needed, i can add it back in first NY commit.

**Comment by GoDhAnD-897** [comment]
I would be very happy :)

**Comment by jeefo** [comment]
Reverted: https://github.com/jeefo/yapb/commit/7d5878891650c65408d51fc5d25f47b495626087
