### ISSUE TITLE
Цели ботов и стычки и пожелания

### ISSUE THREAD

**Issue by sergiopoverony** [jeefo/yapb#5]
При потере ботом бомбы. часть ботов приходят на место закладки бомбы и там сидят. За бомбой не идут. Менты - охраняют выпавшую бомбу корректно. 
Если у ботов кончились патроны они будут стоять и смотреть друг на друга. не подвижно.
Если боты были оба с гранатами - аналогично. Гранату не кидают. Стоят смотрят друг на друга. 
Нужен сквар убийства всех ботов. 
Нужен сквар запрета садится и кемперить. 
На скрине это считай было начало раунда - до конца времени они так и стояли... 
![screenshot_2016-01-03-15-38-53](https://cloud.githubusercontent.com/assets/5286127/12078365/4846212c-b230-11e5-83cc-29de8e3894d7.png)

**Comment by jeefo** [comment]
"Если у ботов кончились патроны они будут стоять и смотреть друг на друга. не подвижно."
"Если боты были оба с гранатами - аналогично. Гранату не кидают. Стоят смотрят друг на друга. "
частично пофиксил, завтра залью.

"Нужен сквар убийства всех ботов. "
yb killall

"Нужен сквар запрета садится и кемперить. "
добавил yb_camping_allowed 0/1. Завтра залью изменения

**Comment by sergiopoverony** [comment]
Отлично - сборкой клиента с ND ?

**Comment by jeefo** [comment]
Коммит закинул. У меня щас нет доступа к машине для сборки под андройд.

Попроси mittorn || a1batross.
