### ISSUE TITLE
Suggestion>Generate Automatic Navigation Waypoints for maps

### ISSUE THREAD

**Issue by MAXBURAOT** [jeefo/yapb#50]
I would like to suggest for future YaPB version to have a function to generate Automatic Navigation Waypointing for CS maps, like Realbot and CSBot using. :)

**Comment by jeefo** [comment]
Nice, but too much work for a hobby project)

**Comment by ViBE-HU** [comment]
just a theoretical question: what if someone fund a bit? i'm pretty inactive nowadays but i'm still very impressed how sleek is yapb and i'm using it on my server. but the bugs what I reported in several ways are still exist and would be good to see a bug free build. hope i'm not the only one who still interested.

**Comment by jeefo** [comment]
Hi!

It's never was "for money" Report bugs, i will have some time to do  something in next year.
