### ISSUE TITLE
valve id

### ISSUE THREAD

**Issue by csoyuncu** [jeefo/yapb#52]
can you add unuqiute id for bots?

example when i write status my console, dont write BOT..

**Comment by jeefo** [comment]
Hello it's possible to fake ID's, however it's not easy way for original HLDS.

I can provide some patches for rehlds, and xash3d if u want.

**Comment by csoyuncu** [comment]
@jeefo can you send me please bot id patch. I use rehlds on linux centos. thank you very much

**Comment by xpt1x** [comment]
@jeefo status of this issue ?
I use REHLDS
