### ISSUE TITLE
yb_join_after_player bug

### ISSUE THREAD

**Issue by GoDhAnD-897** [jeefo/yapb#53]
If "yb_join_after_player" is set to 1,
the bots join even before you have chosen a team.

Solution:
manager.cpp:483-486
```
if (yb_join_after_player.GetBool () && !numHumans)
    desiredCount = 0;

int numHumansOnTeam = yb_autovacate_smart_kick.GetBool () ? GetHumansJoinedTeam () : numHumans;
```

change to:

```
int numHumansOnTeam = yb_autovacate_smart_kick.GetBool () ? GetHumansJoinedTeam () : numHumans;

if (yb_join_after_player.GetBool () && !numHumansOnTeam)
    desiredCount = 0;
```

**Comment by VladAndroidGamer** [comment]
I`m send a pull request to developer. Thanks :)

**Comment by jeefo** [comment]
Thank you @VladAndroidGamer for PR and @GoDhAnD-897  for fix. Should be in latest build here: https://yapb.ru/files/releases/latest/
