### ISSUE TITLE
Список ошибок YaPB

### ISSUE THREAD

**Issue by VladAndroidGamer** [jeefo/yapb#59]
Баги которые я нашёл при игре с ботами. Они проявляются в версии 2.8.
1. Не кемперят в кемперских точках.
2. Часто говорят одну и ту же фразу
3. Иногда не могут разминировать бомбу.
4. Не ставится обратный прыговой путь (вместо этого добавляется флаг "Важный для террористов")
5. Не вычисляется автоматически радиус вэйпоинтов
6. Не закрывается меню изменения радиуса точки
7. Боты не заходят в игру когда меняешь карту
8. VIP пытается взять оружие и прыгает над ним (и это он делает почти весь раунд)
9. Не отображается версия YaPB после загрузки карты вместо этого пишется буква "s" с отступом в начале (в том месте где отображается чат)
10. Некоторые подразделы меню не переведены. (По крайней мере на русский язык)

**Comment by VladAndroidGamer** [comment]
Дебаг нужен?

**Comment by jeefo** [comment]
Постраюсь в ближайшее время поправить хоть от части... Катастрофа со свободным временем.

**Comment by jeefo** [comment]
@VladAndroidGamer  по пункту 8, не получается воспроизвести, можно подробней?

**Comment by jusetheelite** [comment]
Jeefo, ты снова взялся за разработку yapb?) Сколько лет, сколько зим...)

**Comment by VladAndroidGamer** [comment]
@jeefo Если хотитк подробнее то:
Этот баг проявляется на ВСЕХ картах типа AS. Особенно заметно на карте !as_fortress. Там оружие лежит прямо под ногами VIP. И он полраунда там прыгает. На других AS картах, когда VIP нашёл какое-нибудь оружие у трупа, то он тоже прыгает над ним.

**Comment by VladAndroidGamer** [comment]
Позже поставлю обновление. Кстати у меня Windows, а вы мне дали SO библиотеку (для Linux). А хотя вы же не знали какая у меня ОС

**Comment by VladAndroidGamer** [comment]
Установил последнюю версию для Windows. Помоему, остались те-же баги.

**Comment by jeefo** [comment]
Под винду пока не собирал... Свежие.  Вечером выложу.

**Comment by jeefo** [comment]
@jusetheelite хера себе) какие люди)

**Comment by jeefo** [comment]
@VladAndroidGamer https://transfer.sh/4YUkq/yapb.dll вот свежая, за стабильность пока не ручаюсь, но проверить можно. Баг с випом пофиксил тоже.

**Comment by jeefo** [comment]
@VladAndroidGamer не против если твой пак залью в wpdb на yapb.ru?

**Comment by VladAndroidGamer** [comment]
@jeefo конечно я не против! Заливайте

**Comment by jeefo** [comment]
По поводу навигации, можно демку и на какой карте?

По чаттеру понял, посмотрю после отпуска.

**Comment by VladAndroidGamer** [comment]
@jeefo на всех картах. Хорошо, скину демку. Попозже

**Comment by VladAndroidGamer** [comment]
@jeefo вот демки: http://rgho.st/7MqQw5C9d
и http://rgho.st/7b8lDqfgf
Во второй демке боты ходят туда-сюда дольше. Карты для демок присутствуют в архивах

**Comment by VladAndroidGamer** [comment]
@jeefo. Я заметил ещё один баг. Иногда боты стоят и не стреляют друг в друга. Демка:
[standingbug.zip](https://github.com/jeefo/yapb/files/2282928/standingbug.zip)

**Comment by Overitab** [comment]
Пути которых нет в базе рабочих и нерабочих всего 491 https://mega.nz/#!H8ggjIzL!_xuBqofqmYzN681051GDxmHMGT8kf1KcJrWjBhR8E5M
также пофикшены 4 карты aim_00.pwf , aim_ak_thc.pwf, aim_ak-colt2.pwf, aim_arena.pwf

**Comment by Seregassss** [comment]
Здравствуйте! У ботов проблемы с квотой, как при смене карты так и во время захода и выхода людей.  А ещё похоже не работает уровень сложности. Очень жду исправлений! Боты нравятся но эти баги...

**Comment by jeefo** [comment]
Квота пофикшена в bugfix ветке.

https://yapb.ru/ci/project/release/yapb.so

По фейкпингу посмотрю.

Сложность меняется, но там да, они даже на нулевой сложности сложные.

**Comment by VladAndroidGamer** [comment]
@Overitab удали мои вэйпоинты со сборника! Там некоторые вэйпоинты сохранены с ошибками. Я потом исправлю.

**Comment by Overitab** [comment]
Я и не говорил что все мои , где ники DarkFlame , beria и ещё другие, сейчас не помню уже все, это мои , остальные находил в интернете. Исключил с папки рабочих и нерабочих , смотрю получилось боольшая база вот и скинул тут.  Лучше напиши свои контакты , дискорд или скайп скооперируемся соберём лучший пак путей.

**Comment by VladAndroidGamer** [comment]
@Overitab я в  Discord'е "VladAndroidGamer". Такой же ник как здесь.

**Comment by jeefo** [comment]
> Мой конфиг для строительства путей , делаю через подбота,

А почему через подбота?)

**Comment by Overitab** [comment]
Просто дело привычки, а будет большая разница если делать через yap ? лучше для путей? Кстати хотелось бы автоматическое создание путей как у realbot в процессе игры с записью движений всех  игроков на сервере и потом уже ручное редактирование и удаление смертельных путей падений например и добавление точных прыжков, можно даже без обратной совместимости с podbot. Nav система zbot тоже считаю не выход, для прыжков в любом случае нужна система точных поинтов.  Считаю так будет и быстрее и качественнее, пусть размер файла путей будет хоть 10 мегобайт, увеличить плотность точек поинтов + запись повторяющихся движений игрока, выглядывание из  -за угла и тд , то есть запись истории поведения игрока по точкам и повтор этих движений ботом .  Текущей системы уже не хватает для качественного геймплея

**Comment by jeefo** [comment]
Sad but true.

Это не реализуемо в подботе.

Если баги остались из списка выше, просьба открыть новый тикет.
