### ISSUE TITLE
Разминирование. 

### ISSUE THREAD

**Issue by sergiopoverony** [jeefo/yapb#6]
Вроде перестали кемперить. Но и бомбу не могут разминировать... скрин пример. Они после установки бомбы там и 4-м стоять могут  - мечтать о насущем и миссии... 
![screenshot_2016-01-05-22-11-11](https://cloud.githubusercontent.com/assets/5286127/12121905/c7bbfc86-b3f9-11e5-85b4-46753cf206a2.png)

**Comment by jeefo** [comment]
У меня такого поведения не наблюдается.

Обязательно yb version нужен. + Когда они тупят, yb_debug 2, и подлететь к тупящему боту и снять скрин.

**Comment by jeefo** [comment]
Помойму понял в чем проблема, она должна была наблюдаться после нескольких раундов игры.

В текущем коммите должно быть поправлено.

**Comment by sergiopoverony** [comment]
Гуд. отлично.
