### ISSUE TITLE
csdm_reapi + yapb вопрос

### ISSUE THREAD

**Issue by chihuahuashka** [jeefo/yapb#73]
Возможно ли в дальнейшем подружить ботов с этим режимом? https://dev-cs.ru/threads/3814/  с ним они не знают что включен ксдм, и про ffa режим тоже не знают. Или просто регулировать их поведение кварами (yb_csdm, yb_ffa)

**Comment by jeefo** [comment]
Приветствую.

Есть вариант попросить автора зарегить квары mp_freeforall & csdm_active ? Я думаю не только YaPB использует это для определения CSDM.

**Comment by jeefo** [comment]
В последней ревизии добавил `yb_csdm_mode`

0 - autodetect
1 - csdm team mode
2 - csdm ffa
3- csdm force disable

Если еще актуально.
