### ISSUE TITLE
Need Yapb csdm ffa mode

### ISSUE THREAD

**Issue by Left4Dad** [jeefo/yapb#74]
Hi..I was wondering if you can add yapb bots to have a freeforall mode. The command mp_freeforall only works for zbots and zbots will start killing each other. But yapb bots will never try to kill their own team. Is there anyway to make yapb bots kill their own team so that it acts like a deathmatch? Is there any command for the yapb to have ffa mode? Or can u make this happen? Plz i need to play ffa mode with yapb bots so badly!! Please..

**Comment by jeefo** [comment]
Hi...

Can u try this build? https://yapb.ru/files/binaries/5503/release/

**Comment by Left4Dad** [comment]
Btw, i am playing in android. So should i replace the files given by you? And what should i do next?? If i set mp_freeforall, will yapb bots shoot each other??

**Comment by jeefo** [comment]
Ouch... Client should be recompiled. I will try to recompile Friday and give you APK.

**Comment by Left4Dad** [comment]
Thank you so much. You are blessed :)

**Comment by Left4Dad** [comment]
So after u recompiled, what commands should i use to make yapb kill each other? Should i use mp_freeforall??

**Comment by jeefo** [comment]
Yup.

**Comment by Left4Dad** [comment]
Thank you so much. You had earned my respect :)

**Comment by Left4Dad** [comment]
Can u also add the yapb bots to have the ability to use silencer for weapons like m4a1 and usps? Plz add this in the apk as well. Dont let all bots use silencer when they buy m4a1 or usp. Let some yapb bots use silencer and some others dont use silencer. Is this possible??

Second, can u add a command that can enable or disable the yapb bots ping numbers?

Third, can u add a command for fake ping numbers for yapb bots? Because the ping is always 0 for yapb bots. I hope u can add fake ping numbers that will increase and decrease overtime. I want the ping to be realistic so that when i play against these bots,it feels real! If u can do all these request, i am speechless. There is only one word to describe you if u can do these requests for me...and the word is "LEGEND".

Make all of this request be on that apk that u said before

**Comment by Left4Dad** [comment]
So can u do it?

**Comment by jeefo** [comment]
About Silencers:
That's working like u said. Not every bots using silencer, there's many factors to bots to use silencers.

About Ping:
It's not possible server-side, you need to ask FWGS Dev team, it's should be added client-side.

//
// Controls what latency will be shown in scoreboard for bots.
// 
// Available values:
//  0 - Nothing is displayed.
//  1 - "BOT" latency is displayed.
//  2 - Simulating human latency.
//
yb_latency_display "0"

**Comment by Left4Dad** [comment]
So let me get this straight, so u are making the mp freeforall to work on yapb bots. And ur also adding ability for yapb to use silencers. Is that correct??

**Comment by Left4Dad** [comment]
Plz..now i saturday😂. I really want that apk.

**Comment by Left4Dad** [comment]
I am waiting.... XD

**Comment by ViBE-HU** [comment]
i already mentioned a while that the fake ping for bots not working. first it worked sometimes but after an update it's absolutely not shows up.

**Comment by Left4Dad** [comment]
Its ok. Dont add that fake ping feature. Just add ability for some bots to use silencers and also mp_freeforall mode for that recompiled apk :). Well...i guess i am waiting for that apk again :D

**Comment by Left4Dad** [comment]
Is the apk done? I need to test it out so badly

**Comment by Left4Dad** [comment]
It has been a week. Still no apk? :(

**Comment by ViBE-HU** [comment]
dude, people doing their own project at their spare time nowadays.

**Comment by Left4Dad** [comment]
Wait...is Jeefo and Vibe different person or same? I am confused😂. But I just wanna know when I can get the apk...
