### ISSUE TITLE
Recompile Apk and some android problems

### ISSUE THREAD

**Issue by Left4Dad** [jeefo/yapb#77]
Hello Jeefo, I really hope you see this and do the recompiled apk for me.

In the android version, I need mp_freeforall to work, I want some yapb bots to use silencer. Third, plz fix issue for low-difficulty bots because they never try to defuse the bomb. Fourth, the lowest difficulty 0 and 1 bots will not throw grenades, plz let them throw grenades. Fifth, for yb_difficulty 0 and 1, the bots are already kinda good. For difficulty 2 to 4 is extremely pro like they are cheating. For difficulty 2, can u make them react slower abit? And also make the difficulty 2 bots not to aim so well. Difficulty 2 is already like playing against professional level. It is very hard due to the bots have aimbot and can immediately kill you cuz they always aim for the head. For difficulty 0,1,2,3, can you make them have shaky aim? So that the bots dont play like a aimbot hacker. Maybe you can make them aim below the head or make their aim abit shaky. Hope you can make this apk as fast as you can Sir.

Btw, a random question: how to make yapb bots to press a button? I dont think there are any waypoints for bots to do that. Will yapb bots press a button whenever they want? Or is it not possible for them to press a button?

**Comment by Left4Dad** [comment]
Also, how do you recompile the apk? Maybe you can teach me so that u can just give me the files, and i will compile it myself😀

**Comment by VladAndroidGamer** [comment]
The Android version of YaPB is compiled with the CS16Client. Сreator of CS16Client is a1batross. And he assembles it with a new version of YaPB

**Comment by jeefo** [comment]
I will ask a1ba to recompile after some fixes.

**Comment by Left4Dad** [comment]
Thank you plz add these: 

1)make mp_freeforall 1 and 0 works with yapb.

2)yapb bots use silencer. But dont let them use silencer every time. Make it random. Or make a command that allow or disallow yapb to use silencer. Here is an example: yb_silencer 0 / yb_silencer 1

3)Third, plz fix issue for low-difficulty bots because they never try to defuse the bomb.

4) the lowest difficulty 0 and 1 bots will not throw grenades, plz let them throw grenades. 

5) Let yapb bots use flashlight on dark areas. Add a command : yb_allow_flashlight 1 / yb_allow_flashlight 0. (If u can add this, it will be great)

6) [Mention on Above ] for yb_difficulty 0 and 1, the bots are already kinda good. For difficulty 2 to 4 is extremely pro like they are cheating. For difficulty 2, can u make them react slower abit? And also make the difficulty 2 bots not to aim so well. Difficulty 2 is already like playing against professional level. It is very hard due to the bots have aimbot and can immediately kill you cuz they always aim for the head. For difficulty 0,1,2,3, can you make them have shaky aim? So that the bots dont play like a aimbot hacker. Maybe you can make them aim below the head or make their aim abit shaky.

Do u have any social media so that i can talk to u??
