### ISSUE TITLE
Yapb limited waypoints (HELP)

### ISSUE THREAD

**Issue by Left4Dad** [jeefo/yapb#78]
Hello, so i have been playing on a map which is huge. I asked my friend to make the yapb waypoints on that map for me but there is a huge problem. The waypoints are limited :(

So there are other areas and places that he cannot add waypoints aymore because all waypoints have been used. I was wondering anyone can add a feature where the yapb waypoints are unlimited or add more waypoints. Plz, someone plz fix this, btw, my friend is using mobile cs 1.6 version to create waypoints. So can anyone plz help??

**Comment by Overitab** [comment]
yapb already has the raised limit in comparison with PodBot at PodBot 1024 points
give me waypoint from map maybe you friend make ways from podbot not from yapb

**Comment by Left4Dad** [comment]
Hello. In android, there was only yapb and zbot supported.  The "Yapb" was even written there on cs client when we open it up. And i am also pretty sure that its yapb because i have a file on android called addons. And there is a yapb file on it. So maybe android only support 1024 points?? I am not sure. But are u saying that ur able to do those waypoints for me on that huge map??

**Comment by Overitab** [comment]
waypoint file .pwf same android and PC. What name of map ?

**Comment by Left4Dad** [comment]
Can you give me your fb messenger?i will send you link there. Here is abit difficult for me. Whats your fb messenger name?

**Comment by Overitab** [comment]
> Can you give me your fb messenger?i will send you link there. Here is abit difficult for me. Whats your fb messenger name?

facebook.com/gmtremor

**Comment by Overitab** [comment]
I confirm it is necessary to add the raised limit on quantity of points, podbot all the same was not updated long ago and is already not strongly relevant

**Comment by jeefo** [comment]
2048 will be enough?

**Comment by Left4Dad** [comment]
Hmm..can u do 3048 instead? Its better for larger maps. There are more larger maps in 1.6 so i suggest 3048. 2048 is still not enough

**Comment by jeefo** [comment]
https://yapb.ru/files/binaries/5584/

This build rises waypoint max count to 3072,

However next builds will have limit of 2048. 3072 making bots to eat too much CPU power.

**Comment by Left4Dad** [comment]
Than make it to 2048 than :)

**Comment by jeefo** [comment]
Nodes limit raised.
