### ISSUE TITLE
Bot AI sucks + changing settings in the cfg file doesn't work

### ISSUE THREAD

**Issue by leopard20** [jeefo/yapb#8]
Your bots never go after their primary goal. 
For example a terrorist doesn't plant the bomb, or counter terrorists don't rescue the hostages, they just move around the map and kill each other.
Also they always cheat. They throw grenades right under your feet by just listening to your footsteps! Seriously, CS original bots are a lot better, and smarter.
Also when change settings in the cfg file(for example the difficulty level, quota, etc) it doesn't work.

**Comment by jeefo** [comment]
Well, use "original cs bots" then.
