### ISSUE TITLE
A few recommendations and problems

### ISSUE THREAD

**Issue by Nakaxhan** [jeefo/yapb#80]
I love these bots too much (**imo** is the best), but I found a couple of mistakes that put them at a disadvantage and I think they are easy to solve. 

**They do not use shotguns over long distances**
It is logic that both, the m3 as the xm1014 does not make much damage even an elephant at long distances, but that doesn't mean bots still stand aiming without shooting (and this affects a lot the gun game matchs). 
My possibles solution are:
Bots must change to their secondary weapon in a long distance encounter 
Bots must "escape" or get closer to the enemy

**They trying to use snipers over very short distances**
Something like as the previous
Possible solution:
Bots must change to their secondary weapon in a very short distance encounter 

**Bots don't buy Desert Eagle**
I've seen them use it (of course, when they get it from a pick up) and they are very effective in short and long distance, but it's sad that they don't buy it only for save some bucks (even though buying a desert eagle can be an investment)

I think that's all, but I'm also very grateful for your work and dedication to this.

PS: Do you have a paypal account where I can leave a tip?

**Comment by Left4Dad** [comment]
Everything you said were actually already fixed. 1) The problem for bots using m3 and xm1014, can be fixed if you set the difficulty higher. I had tested it. They will use pistols instead on long distance. 2) The yapb bots do not use awp on short distances. I have played so many matches with those bots and i know it. They only use sniper in shot distances if you actually set the yapb bots to the lowest difficulty. So plz change your difficulty. 3) The deagle problem is acceptable. Bots rarely buy pistols and thats their problem. But can you close this issue and open up a new one for the deagle problem? I am pretty sure Jeefo will ignore the first and the second problem since that it was already implemented on the yapb bots. You just gotta change t

**Comment by Overitab** [comment]
for use deagle need edit this cfg file general.cfg
`// ------------------------------------------------------------------------
// This file is part of Yet Another Ping Of Death Bot Configuration Files.
// Copyright (c) 2003-2015, by YaPB Development Team.
//
// Please check out the documentation, before altering config files.
// ------------------------------------------------------------------------

// Numbering of the weapons:
// 0 - KNIFE
// 1 - USP
// 2 - GLOCK18
// 3 - DEAGLE
// 4 - P228
// 5 - ELITE
// 6 - FIVESEVEN
// 7 - M3
// 8 - XM1014
// 9 - MP5NAVY
// 10 - TMP
// 11 - P90
// 12 - MAC10
// 13 - UMP45
// 14 - AK47
// 15 - SG552
// 16 - M4A1
// 17 - GALIL
// 18 - FAMAS
// 19 - AUG
// 20 - SCOUT
// 21 - AWP
// 22 - G3SG1
// 23 - SG550
// 24 - M249
// 25 - SHIELD

//
// Following are Tables which specify which Team is allowed
// to buy a weapon on a Map. You can also use it to allow/disallow
// Weapons for a Team or a Map/Gamemode (remember that some
// Weapons are team-specific and can't be bought by another team).
// -1 = Disallow Buying for any Team
// 0 = Terrorist Team only
// 1 = CT Team only
// 2 = Can be bought by both Teams
// Standard Weapon Tab for CS & DE Maps
//
MapStandard = -1,0,-1,2,-1,0,1,2,2,2,-1,2,-1,-1,0,0,1,0,1,1,2,2,0,1,2,1
MapAS = -1,-1,-1,2,-1,0,1,1,1,1,1,1,0,2,0,-1,1,0,1,1,0,0,-1,1,1,1

//
// Grenade buying percentage
// HE, FL, SMOKE
//
GrenadePercent = 98,75,60

//
// Bot Economics. From left to right.
//
// 1 - If bot's money more than the value specified here. He can buy the primary weapon.
// 2 - If bot's money more than the value specified here he will not buy SMGs (MP5,  MAC10, TMP, P90, UMP45, SCOUT) (only for CTs) (+ 8/9/10)
// 3 - If bot's money more than the value specified here it will not buy SMGs (MP5, MAC10, TMP, P90, UMP45, SCOUT) (only for Ts) (+ 8/9/10))
// 4 - If bot's money more than the value specified here he can buy shotguns (M3, XM1014).
// 5 - If bot's money less than the value specified here he cannot buy shotguns (M3, XM1014).
// 6 - If bot's money more than the value specified here he can buy AWM, SG550, G3SG1, M249.
// 7 - If bot's money less than the value specified here he cannot buy AWM, SG550, G3SG1, M249.
// 8 - How much money bot leaves a prostock, at purchase of the primary weapon (only for type of behaviour - Normal)
// 9 - How much money bot leaves a prostock, at purchase of the primary weapon (only for type of behaviour - Agressive).
// 10 - How much money bot leaves a prostock, at purchase of the primary weapon  (only for type of behaviour - Careful).
// 11 - If bot's money more than the value specified here. He can buy the shield.
//
Economics = 1550,2100,2100,4000,6000,7000,16000,1200,800,1100,3000

//
// The following Tables stores the Weapon Priorities of the Bots depending on
// Personality (it affects buying & picking up better weapons from the ground).
//
PersonalityNormal = 00,02,01,04,05,06,03,12,10,24,25,13,21,15,16,22,23,20,19,08,14,07,11,09,17,18
PersonalityRusher = 00,02,04,05,01,06,03,24,25,22,23,20,10,12,13,07,08,21,11,09,15,19,17,18,16,14
PersonalityCareful = 00,02,01,04,05,06,03,12,20,13,11,25,18,17,15,19,16,14,10,22,24,08,09,21,07,23`

**Comment by Nakaxhan** [comment]
I always play with the maximum difficulty, but just yesterday I tried the last update available in the 5503 bin and the difference is incredible, although I didn't test the shots at long distance from the shotguns so maybe later i will try a gun game for it. Yes, the deagle Problem maybe it has a lot to do with the economic rounds, I started to notice that they only buy it when they have an amount of money higher than 8-10k so I'm going to try Overgab's cfg and in a few minutes I will give my answer to it.

**Comment by Nakaxhan** [comment]
Well, I tested the Overitab's cfg and I do not notice much difference respect to the deagle problem, but in general, I think I'm satisfied.
I'm going to close this issue and if yeefo wants a donation he can contact me via mp
