### ISSUE TITLE
yb_quota_mode with fill value isn't working correctly

### ISSUE THREAD

**Issue by andrewlindberg** [jeefo/yapb#81]
As the title says, if yb_quota_mode is fill only 2 bot connects to the server and after 5-7 minutes the others (in my case the others 8, cause I used yb_quota 10) joined the server. All info about the server is in the gif below

I used version from release and version with latest commits (february)

![2019-04-20-17-52-05](https://user-images.githubusercontent.com/9461696/56459106-c0f4f000-6397-11e9-9f4a-42f5baefc8db.gif)

**Comment by jeefo** [comment]
Thank you. Will try to fix.

**Comment by jeefo** [comment]
Any chance to test? 

https://yapb.ru/files/binaries/5584/

**Comment by andrewlindberg** [comment]
Sometimes it kicks bot from opponent team, but sometimes it works correctly.
 
Modified cvars:
yb_quota 10
yb_quota_mode fill
yb_chat 0 

https://www.youtube.com/watch?v=Xv7__0XlH9Y

**Comment by jeefo** [comment]
So the main problem solved. Only the incorrect kick of bot from team. I.e. joining CTs causes TERRORIST (instead CT) bot to left so teams becomes uneven, and vice versa. Yup ?

**Comment by andrewlindberg** [comment]
Exactly

**Comment by jeefo** [comment]
https://yapb.ru/files/binaries/5584/

Same day-build. Version changed. Should fix this problem.

**Comment by andrewlindberg** [comment]
Bug appears only when joining CT side (one terrorist bot is kicked) . When joining Ts side, it works correctly.

https://www.youtube.com/watch?v=uqv4KsRKziM

**Comment by jeefo** [comment]
Oh well... Rebuild should be done already. It's should work now as expected... 

Thank you for testing.

**Comment by andrewlindberg** [comment]
Fixed. Thanks!

**Comment by bobito1993asd** [comment]
jeefo brother help me it doesn't work properly nor does it open the menu
