### ISSUE TITLE
Русская документация ботов YaPB

### ISSUE THREAD

**Issue by Vladislav4KZ** [jeefo/yapb#82]
Я закончил перевод, и хотел чтобы вы добавили его на сайт yapb.readthedocs.io
Мой перевод есть на GitLab (ветка russian): https://gitlab.com/S_Vladislav/yapb-readme/tree/russian

Позже, я попытаюсь дополнить документацию, я знаю что можно добавить к инструкции по созданию вэйпоинтов.

**Comment by jeefo** [comment]
Спасибо! Закину, когда вернусь из отпуска)

**Comment by jeefo** [comment]
https://yapb.readthedocs.io/ru/latest/
