### ISSUE TITLE
Re-create waypoints for Standard Maps.

### ISSUE THREAD

**Issue by jeefo** [jeefo/yapb#83]
Hello.

As for update process, can anybody re-create standard waypoints for dust2, aztec, inferno, nuke and so on? Actually quality of "official" waypoints isn't nearly perfect.

And well, you have max out waypoint number > than 1024 now. So you're not limited anymore.

**Comment by Left4Dad** [comment]
Sure man. My friend can help you with that. :)
He made perfect waypoints for me too. But can u tell me what map waypoints u want more specifically??

Than make it to 2048 than :)

Btw, can u check this? Here are the things that needed to be added. #79 (comment)

**Comment by jeefo** [comment]
I have checked #79. Taked it into the account.

D2 & Aztec, the favorite maps )

**Comment by Left4Dad** [comment]
Dust 2 abd Aztec only?? XD
Do u have any social media? I will send u the link for download.

**Comment by jeefo** [comment]
telegram @dmitryzhukov

**Comment by Overitab** [comment]
i will make today tomorrow

**Comment by Overitab** [comment]
bots have comand now  yp wp clean  ?

**Comment by jeefo** [comment]
Not yet. In process.

**Comment by Overitab** [comment]
ways for dust2, nuke, aztec
https://cloud.mail.ru/public/2hbL/4vGpdSwEq

**Comment by jeefo** [comment]
> bots have comand now yb wp clean ?

https://yapb.ru/files/binaries/5586/

Needs testing.

**Comment by ulist** [comment]
Jeefo gay

**Comment by jeefo** [comment]
@Overitab can u re-upload?

**Comment by Nakaxhan** [comment]
Do you still need help?
I can make the waypoints that you need in a couple of days

**Comment by seisdr** [comment]
jefoo gay

**Comment by jeefo** [comment]
@Overitab has made the most work. Thank for offer @Nakaxhan
