### ISSUE TITLE
Bots Still Spamming "Follow Me, Sector Clear, Affirmative, Need Backup" Like Radio Commands.

### ISSUE THREAD

**Issue by PRinceBhai** [jeefo/yapb#84]
I know this is accounted but please can this be not resolved? The latest release have this.
If not can someone please tell me which version have this fixed? It's seriously annoying.

**Comment by jeefo** [comment]
Chatter or radio?

**Comment by jeefo** [comment]
It's should be finally fixed in latest builds...

**Comment by jeefo** [comment]
Closing as fixed.
