### ISSUE TITLE
Added new Simplified Chinese (chs_chat) and Traditional Chinese (cht_lang, cht_chat).

### ISSUE THREAD

**Issue by HaoJun0823** [jeefo/yapb#88]
I don't know if this project is still being updated. So when I found it, I added a chat between Simplified Chinese and Traditional Chinese, as well as a menu of Traditional Chinese (this file refers to the original Simplified Chinese menu).
Regarding the name files, I have no translations because they can remain the original.

I hope this will help with this project.

If you have any needs, you can contact me.

[cht_chat.txt](https://github.com/jeefo/yapb/files/3365596/cht_chat.txt)
[cht_lang.txt](https://github.com/jeefo/yapb/files/3365597/cht_lang.txt)
[chs_chat.txt](https://github.com/jeefo/yapb/files/3365598/chs_chat.txt)

**Comment by HaoJun0823** [comment]
I don't have a Pull Request because this does not seem to be part of the source code.

**Comment by jeefo** [comment]
Thank you. Will include it in next release.
