### ISSUE TITLE
Waypoints Search for cs_min and cs_assault_shadow

### ISSUE THREAD

**Issue by Infamous2017** [jeefo/yapb#91]
Waypoints Search for cs_min and cs_assault_shadow

https://gamebanana.com/maps/177254

https://gamebanana.com/maps/172761

**Comment by PRinceBhai** [comment]
You just can't do them your self?

**Comment by Infamous2017** [comment]
No. I tried but i am to damn for it :D

**Comment by PRinceBhai** [comment]
ok, i'll get them to you tomorrow.

**Comment by Infamous2017** [comment]
35hp_4  too? that would be great :)

**Comment by PRinceBhai** [comment]
sure, it's pretty easy.

**Comment by Infamous2017** [comment]
Cool - THANKS

**Comment by PRinceBhai** [comment]
https://www.mediafire.com/file/xloyul20z3xvwhz/3pwf.7z/file

**Comment by Infamous2017** [comment]
wow man, BIG BIG thx =)
