### ISSUE TITLE
Gunxp for CT 

### ISSUE THREAD

**Issue by Infamous2017** [jeefo/yapb#92]
Bots should be able to choose Guns when the Mod is Gunxp. =)  Possible to fix this?!

**Comment by PRinceBhai** [comment]
It's not a bug or something, they are designed to BUY the guns with MONEY, so jeefo can't program them according to any third party plugin/mod. Which will take a hell of a time.

**Comment by jeefo** [comment]
I will take a look at this little bit later.

**Comment by jeefo** [comment]
Sorry, mod authors should add correct support for bots.
