### ISSUE TITLE
yapb causes xash3d to crash when removing a bot

### ISSUE THREAD

**Issue by bobbydee1x** [jeefo/yapb#93]
Yapb works fine in xash3d until you try to kick a bot or all of them. Error says "NET_SendPacket: bad address type 0"

CS1.3
OS: Windows 10
Xash3D fwgs
yapb-2.9.5395-dev-git341-windows

**Comment by jeefo** [comment]
Hello. Xash3d version?

**Comment by bobbydee1x** [comment]
In Xash3d build 4529 when I kick a bot it disconnects me from the game but in Xash3d FWGS 0.99 game crashes entirely.

**Comment by jeefo** [comment]
Sorry, can't reproduce.

https://drive.entix.io/f/8234b257341b4b7097ab/

Can you dump all the game directory, and send link to d@entix.io ?

**Comment by bobbydee1x** [comment]
I have a poor internet connection is it okay if I just upload the exe and the dll's that I'm using?

**Comment by jeefo** [comment]
EXE, dlls and cstrike/mp.dll.

**Comment by bobbydee1x** [comment]
here are the cl_dll mp.dll and the xash 4529 build that i'm using!

https://drive.google.com/file/d/1bAYZqffc4grIhwF1IZx-3W6Oaw2Jfiz9/view?usp=drive_open

**Comment by jeefo** [comment]
Well. It's actually not a FWGS fork of Xash3d, it's original Xash3d by Uncle Mike. And it's crashing somewhere inside engine.

Try to use **real** FWGS fork from here: https://github.com/FWGS/xash3d/releases

**Comment by bobbydee1x** [comment]
I tried to use the updated Xash3d-FWGS engine and the problem is also present. https://github.com/FWGS/xash3d-fwgs/releases

**Comment by jeefo** [comment]
It's not engine that you want.

https://github.com/FWGS/xash3d/releases correct one.

The xash3d-fwgs is currently under development.
