### ISSUE TITLE
New suggestions, Bugs and Ideas

### ISSUE THREAD

**Issue by Left4Dad** [jeefo/yapb#94]
Here are the final things that should be added and fix so that yapb will be more fun and making it look realistic. [YAPB WILL BE BETTER]

When yapb bots zoom using snipers, and when the bot using sniper saw the enemy and when the enemy left their sight, the bots unzoom the scope too fast. Its not realistic. Plz make them zoom abit longer before unzooming. Make it 2secs before unzooming the sniper.

Make afk yapb bots. I know this sounds dumb, but its a cool feature. There is once i played yapb and there is a bot in my team that goes afk. Its so realistic. Maybe its a bug. But can you add this plz??? Its fun. Add this function using a command like for example, yb_afk 0 means all bots will not be afk, and yb_afk 1 means bots sometimes goes afk. Make the max number of 1-3 bots that goes afk. And make it super random and very rare. Hope u can add this. And remember, make it rarely happen.

Make bots balance themselves using all grenades. Yapb bots prefer smoke grenade more. Plz balance it so that they can use other grenades better.

4)Plz add yb_debug 2. The ones that work is yb debug 0 and 1. Can u make another one? Which is yb_debug 2. Make yb_debug 2 only show these features (Name, Health, Armor, Item, Clip, Ammo and money). Thats all. Dont add the viewable waypoints where the yapb will walk to certain places with a line that they will follow just like in yb_debug 1. Add a yb_debug 2 with only those things plzz.
Yb_debug 1 is too complicated.

5)Make the yapb always listen to our commands for [Drop C4, Drop weapon, and Make double jump] Sometimes yapb will not drop the c4 or weapons when i use those commands. Make them 100% listen to what we want them to do. And also make them come to where i stand and make a double jump. Sometimes they stand at the wrong position for the double jump and sometimes they ignore to do the double jump and walked away.

Make yapb bots look around while in spawn. This can make it look realistic. In cs1.6 normal bots, they will look at different positions while freezing at spawn. But those bots only look at one direction. Thats all. But for yapb, when they spawn, they only look straight forward and all yapb bots stand in a line like a soldier 😂. Make 1 to 4 bots to look around when they spawn. So that they look like humans. Make them look at different places while freezing at spawn and make them look around like they are searching for enemies or looking at teammates. Do u know how when the yapb bots camp at a place and they will look at one side and then look at the other side? Thats how i kinda want it. (But dont make them look around while buying things. Only make them look around after bots bought their items) Make a command for this if possible. Make two commands like, one will make them not look around in spawn and all bots look the same direction, another will make them look around the area while freezing at spawn. Make it random. Dont make all 4 bots to look around. Make some bots to look around and not all the bots.
7)Can u make the commands to dissapear when we click these commands? Like Drop c4, drop weapon, double jump and finish double jump. Here is my problem. When i click drop c4 or double jump, the commands 1,2,3,4 is still there. We must click 0 to exit the commands. Can u make it more simplier?? Do it this way: if i clicked on 1 or 2 or 3 or 4, the yapb action commands will disapear by itself so that i dont need to press 0 to exit the yapb action commands . This way is much more faster. Plz do it :)

[This is an optional idea]. Since that all yapb bots has aimbot, can u make two seperate commands for two seperate bot playstyle? For example, yb_aimbot 1 means they will play like the way they play right now. They uses aimbots. And another command is yb_aimbot 0 that will disable them to aimlock at their enemies and they will only shoot the enemy if they see their enemy. Plz make these. Its more realistic. For example like cs 1.6 normal bots, they dont have aimbot. So when we go behind our enemy, they wont see us. But for yapb, they will always know where we are😂. So plz add these two commands whether they will use aimbot or will not use aimbot. [This is optional. If u can do this, it will make us have better gameplay experience with yapb bots]. Make yapb aimlock bots to look around quick like in current version. And make yapb without aimlock to look around slower like it was an actual player slowly swiping the screen just like the normal bots in 1.6 where they look around slowly like they are swiping the screen to look. But yapb screen moves fast. U can compare how yapb bots look around and also how the normal bots look around. (Is the cs 1.6 normal bots called zbot? I am not sure so i called it as normal bots)

Make a command for yapb to use or not to use night vision and flashlight. Because i played the apk version that u send me. I see those bots use night vision. But i didnt see them use flashlight yet because i only play for 10 mins. Can u tell me they will use flashlight or not? And have u added any commands for them to allow or disallow to use flashlight and night vision?? Commands MUST BE ADDED in the yapb.cfg file or u can add the ability to buy or not to buy night vsion on the general.cfg file. Because if they use night vsion,it takes much cpu right? So add a command whether they should use it or not. This way is the best.

They switch weapon to quick! For example if a bot has usp and when he saw the deagle on the ground, and when he walks directly to it, he straight away picks it up. Can u make it more realistic? For example if the bot saw that deagle, he will throw the usp away first than only pickup the deagle. Make him throw the usp away before reaching for the deagle. Hope u can do this.

Can u make yapb bots try to shoot or knife small boxes on the floor? For example, i know that yapb will break the vent when the bot get close to it. But i tried and experiment with a map with some small flat boxes on the floor. Bots seem to ignore it. Can u make it shoot or knife small flat boxes or any normal size boxes? Try to make them knife or shoot breakeble objects more often. The best idea is to create a custom waypoint that will make that bot instantly break that object when he comes near it. A custom waypoint is suitable for this situation.

[PLZ DO THIS]. So i have said before that yapb bots at difficulty 0 and 1 does not defuse the bomb, i hope u fixed it in the next update. And also plz make yapb bots to throw grenade and difficulty 0 too. Plz do that. Now for the important part. For difficulty 0 bots, when they get flashed, make them crouch just like in the current version. But for difficulty 1, when they are flasehd, make them stand at their position when they are flashed. Dont make them crouch. When they are flashed, some bots can blindly move around and most of the bots stand still. Remember, dont make them crouch when they are flashed on difficulty 1. Only if the bot has already been crouching in a spot, and when he got flashed, he will still crouch. Hope u understand me and improve difficulty 0 and 1 with the ideas i gave.

Dont make Terrorist bots crouch during bomb planted. Here is what you can do,imagine if there are 5 Terorist and bomb is planted. Make it something like this, 1-2 bots will move around the map to search for enemies (already in current version), another 1-2 bots Stand and camp and wait for enemies to show up. And make only 1 bot that crouch camp while waiting for enemies. This is more balance. Sometimes when i play, most bots crouch camp to protect the bomb. Make them stand camp which is better and more realistic. You can make 2 bots wonder around and 2 bots stand camp and 1 bot crouch camp. Which basically mean make those bots to have a lesser chance to crouch camp. Make more chances for them to wonder and stand camp.

when enabling yb_chat 1, bots will chat, but when i change yb_chat to 0, bots dont chat but when i ask the bots to do double jump, they will send a teammate msg to me saying ok, i will help you...something like that. When yb_chat is 0, can u make them not to say that word? The "Ok i will help you" thing. Plz do it. Thanks alot

I know that yb_walking_allowed 1 means yapb bots can walk and run. And if its set to 0, they can only run. But can you make another one? Yb_walking_allowed 2, which will make them walk ONLY. Can you do this? Juts like the zbot, we can make them able to walk only. I want this feature for yapb. Can u add it? U can use different cmmand for this if you want :)

THANK YOU ONCE AGAIN. YOU HAVE MADE YAPB BETTER EVERY SINGLE TIME!
If u dont understand my requests, feel free to ask me as well. I just want yapb to be realistic and better :)

Need testers for those requested features? I will also help u test the yapb bots as well. Make the apk for me to try it and i will give u feedback :) . Yapb is still the best!

**Comment by jeefo** [comment]
Hello. Can you please split this into separate issues.

**Comment by PRinceBhai** [comment]
Lord, This guy went places.
