### ISSUE TITLE
Pls create Waypoints for Some Maps

### ISSUE THREAD

**Issue by Infamous2017** [jeefo/yapb#98]
PLs create WAYPOINTS for all these Maps ... THX 

1hp_2           https://maps.cs-bg.info/maps/cs/2167/
35hp_elevator       https://gamebanana.com/maps/204786
35hp_freedoom       https://gamebanana.com/maps/204830
1hp_general        https://gamebanana.com/maps/162698
1hp_happy_new_year           http://files.cs-best.org.ua/?do=download&filename=1hp_happy_new_year
1hp_wristhax          https://gamebanana.com/maps/178198
1hp_et_map           https://gamebanana.com/maps/174220
35hp_CYBERSPORT      http://files.cs-best.org.ua/?do=download&filename=35hp_CYBERSPORT
35hp_spiderweb        https://gamebanana.com/maps/204406
35hp_xtreme_2019       https://gamebanana.com/maps/204335
1hp_2_2017          https://gamebanana.com/maps/197004
1hp_gates          https://gamebanana.com/maps/177978
1hp_loco             https://gamebanana.com/maps/178424
1hp_dark             http://files.cs-best.org.ua/?do=download&filename=1hp_dark
1hp_dg          https://gamebanana.com/maps/183003
1hp_flash          https://gamebanana.com/maps/172414
1hp_final             https://gamebanana.com/maps/204063
1hp_final_2          https://www.17buddies.rocks/17b2/View/Map/89211/1hp_final_2.html
1hp_final_3          https://gamebanana.com/maps/200468
1hp_i-qop           https://www.17buddies.rocks/17b2/View/Map/73031/1hp_i-qop.html
1hp_just          https://www.17buddies.rocks/17b2/View/Map/26564/1hp_just.html
1hp_pwr_full     https://www.17buddies.rocks/17b2/View/Map/72986/1hp_pwr_full.html
1hp_rax           https://gamebanana.com/maps/183112
1hp_relux          https://gamebanana.com/maps/183080
35hp               https://gamebanana.com/maps/204293
35hp_arena_v4         https://www.17buddies.rocks/17b2/View/Map/24814/35hp_arena_v4.html
35hp_bnd             https://gamebanana.com/maps/194298
35hp_gx                https://gamebanana.com/maps/204403
35hp_2              https://gamebanana.com/maps/154904
35hp_2009          https://www.17buddies.rocks/17b2/View/Map/24547/35hp_2009.html
35hp_2_css                      https://gamebanana.com/maps/171795
35hp_dust_2017           https://gamebanana.com/maps/196847
35hp_lava_M             https://www.17buddies.rocks/17b2/View/Map/100701/35hp_lava_m.html
35hp_2_night             https://gamebanana.com/maps/191377
35hp_walle             https://gamebanana.com/maps/203578
35hp_super_mario         https://gamebanana.com/maps/159519
35hp_2_fly               https://gamebanana.com/maps/187888
ka_knifebeach  https://www.17buddies.rocks/17b2/View/Map/3828/ka_knifebeach.html

**Comment by Overitab** [comment]
[1hp_2.zip](https://github.com/jeefo/yapb/files/3627584/1hp_2.zip)

**Comment by Infamous2017** [comment]
thx but i need .pwf files and not graph file.

**Comment by Overitab** [comment]
[35hp_elevator.zip](https://github.com/jeefo/yapb/files/3627688/35hp_elevator.zip)
try last build yapb, you use podbot?

**Comment by Infamous2017** [comment]
yeah thx . yes i am using podbot only with .pwf files =)  Thx

**Comment by Infamous2017** [comment]
mhh no more ?
